import {v4 as uuidv4} from "uuid";

const initialUserWords = [
    {
        id: 'sdjk98fskf98s',
        word: 'have the wind at your back',
        partOfSpeach: 'idiom',
        definition: 'Быть в хорошей ситуации, в которой можешь преуспеть',
        russianEquivalent: 'попутный ветер, сопутствует удача',
        isStudied: false,
        userId: 'dlkfjl3487f9s',
    },
    {
        id: 'dlkjf37r98s7df',
        word: 'scorn',
        partOfSpeach: 'verb',
        definition: 'Продемонстрировать презрение (неуважение, считать что-то глупым и не имеющим ценности) к кому-то или к чему-то.',
        russianEquivalent: 'презирать',
        isStudied: false,
        userId: 'dlkfjl3487f9s',
    },
    {
        id: 'fkj39f8dkj3f',
        word: 'favorable',
        partOfSpeach: 'adjective',
        definition: 'дающий преимущества или больше шансов на успех',
        russianEquivalent: 'выгодный, благоприятный',
        isStudied: false,
        userId: 'dlkfjl3487f9s',
    },
    {
        id: 'dskjdfo98djh2',
        word: 'compare',
        partOfSpeach: 'verb',
        definition: 'изучать или искать разницу между двумя или более вещами',
        russianEquivalent: 'сравнивать',
        isStudied: false,
        userId: 'dlkfjl3487f9s',
    },
    {
        id: 'fdslkj3098zdf',
        word: 'massive',
        partOfSpeach: 'adjective',
        definition: 'очень большой по размеру, количеству или числу',
        russianEquivalent: 'огромный, масштабный, крупный, значительный',
        isStudied: false,
        userId: 'dlkfjl3487f9s',
    },
    {
        id: 'elkjv7ds3jhsdi3',
        word: 'indie',
        partOfSpeach: 'adjective',
        definition: 'о компании, магазине и т. п. бизнесе — небольшой и не принадлежащий более крупной компании; инди-музыка, фильмы и т. д.',
        russianEquivalent: 'малый, независимый, "инди", ',
        isStudied: false,
        userId: 'dlkfjl3487f9s',
    },
    {
        id: 'jfd983kjsd8g73',
        word: 'choppy',
        partOfSpeach: 'adjective',
        definition: 'когда волосы в прядке подстрижены разной длиной',
        russianEquivalent: 'рваными прядками, рваная',
        isStudied: false,
        userId: 'dlkfjl3487f9s',
    },
    {
        id: 'fslkjr809d8f3',
        word: 'show through',
        partOfSpeach: 'modal verb',
        definition: 'становиться видимым, заметным, очевидным через что-то другое',
        russianEquivalent: 'рваными прядками, рваная',
        isStudied: false,
        userId: 'dlkfjl3487f9s',
    },
]