export const initialTrainingRoute = [
    {
        id: 'lksdjfl34134',
        userId: 'dlkfjl3487f9s',
        userRoute: [
            {
                id: 'fj234kljfd9s7f',
                name: 'Что такое грамматика',
                link: '/what-is-theory-and-drill-showing',
                partOfGrammarId: 'fsldkjf323235',
                isOpen: true,
                isStudied: true,
                subThemes: [],
                isOpenSubThemes: true,
            },
            {
                id: '23480fjslkdjf',
                name: 'Как строить предложения',
                link: '/how-to-make-sentences',
                partOfGrammarId: "lkdj34234kjkj",
                isOpen: true,
                isStudied: true,
                subThemes: [],
                isOpenSubThemes: true,
            },
            {
                id: 'dfj237s0f8hj4j2l',
                name: 'Что такое «время»',
                link: '/what-is-tense',
                partOfGrammarId: 'fjkl3k480s9fsdf',
                isOpen: true,
                isStudied: true,
                subThemes: [],
                isOpenSubThemes: true,
            },
            {
                id: 'sdflkj234867s9d8',
                name: 'Present simple',
                link: '/present-simple',
                partOfGrammarId: "sdlkjf3487",
                isOpen: true,
                isStudied: true,
                isOpenSubThemes: true,
                subThemes: [
                    {
                        id: 'aslkj340sd9f8',
                        name: 'Present simple (positive statement)',
                        link: '/positive-in-present-simple',
                        partOfGrammarId: "sdlkfjl3427fdjf",
                        isOpen: true,
                        isStudied: true,
                    },
                    {
                        id: 'sdfkjl3029384',
                        name: 'Present simple (negative statement)',
                        link: '/negative-in-present-simple',
                        partOfGrammarId: "lksj347924sdfh",
                        isOpen: true,
                        isStudied: false,
                    },
                    {
                        id: 'ddlkfj234987324',
                        name: 'Present simple (question)',
                        link: '/question-in-present-simple',
                        partOfGrammarId: "dlfkj234jlkj34",
                        isOpen: true,
                        isStudied: false,
                    },
                ]
            },
            {
                id: 'sdfj2l347sdf723j',
                name: 'Present perfect',
                link: '/present-perfect',
                partOfGrammarId: "slkj234234",
                isOpen: true,
                isStudied: true,
                isOpenSubThemes: true,
                subThemes: [
                    {
                        id: 'djfl2308fsdfj',
                        name: 'Present perfect (positive statement)',
                        link: '/positive-in-present-perfect',
                        partOfGrammarId: "sldkfj3247987",
                        isOpen: true,
                        isStudied: false,
                    },
                    {
                        id: 'fdslkj2l3987fsdj2',
                        name: 'Present perfect (negative statement)',
                        link: '/negative-in-present-perfect',
                        partOfGrammarId: "dkfwher9237fsdf",
                        isOpen: true,
                        isStudied: false,
                    },
                    {
                        id: 'sdfj2l3k4987sfj32',
                        name: 'Present perfect (question)',
                        link: '/question-in-present-perfect',
                        partOfGrammarId: "djwlkej2387fsj3",
                        isOpen: true,
                        isStudied: false,
                    },
                ]
            },
            {
                id: 'dlkfj348723984',
                name: 'Conditionals',
                link: '/conditionals',
                partOfGrammarId: "sdlfkj23498s7f",
                isOpen: true,
                isStudied: false,
                isOpenSubThemes: true,
                subThemes: [
                    {
                        id: 'kjsdf2834792837',
                        name: 'conditional 1',
                        link: '/first-conditional',
                        partOfGrammarId: "kjsdf2834792837",
                        isOpen: true,
                        isStudied: false,
                    },
                    {
                        id: 'lsdjf298374',
                        name: 'conditional 2',
                        link: '/second-conditional',
                        partOfGrammarId: "lsdjf298374",
                        isOpen: true,
                        isStudied: false,
                    },
                    {
                        id: 'dfgj2340760235',
                        name: 'conditional 3',
                        link: '/third-conditional',
                        partOfGrammarId: "023984lskdjf",
                        isOpen: true,
                        isStudied: false,
                    },
                ]
            },
        ],
        userThemesRoute: [
            {
                id: 'dfkjl23r7sdf823j',
                name: 'For all occasions',
                link: '/for-all-occasions',
                partOfGrammarId: "fkjrf80s9df83",
                isOpen: true,
                isStudied: false,
                isOpenSubThemes: true,
                subThemes: [
                    {
                        id: 'sldkjf2398f0s9dfk',
                        name: 'Clarify possible misunderstandings',
                        link: '/clarify-possible-misunderstandings',
                        partOfGrammarId: "dkj2387slaflja",
                        isOpen: true,
                        isStudied: false,
                    },
                    {
                        id: 'dflkj98fs098kjfd',
                        name: 'How to be polite',
                        link: '/how-to-be-polite',
                        partOfGrammarId: "flkj2098srjsl9122",
                        isOpen: true,
                        isStudied: false,
                    },
                    {
                        id: 'kj38f0s98fj23f8dsdf',
                        name: 'Set expressions',
                        link: '/set-expressions',
                        partOfGrammarId: "lsd879823skjdhf",
                        isOpen: true,
                        isStudied: false,
                    },
                ]
            },
            {
                id: 'sdlkj23987sd',
                name: 'Restaurants',
                link: '/restaurants',
                partOfGrammarId: "lsd879dlkj823sk",
                isOpen: true,
                isStudied: false,
                isOpenSubThemes: true,
                subThemes: [
                    {
                        id: 'sdlkfj2387sd',
                        name: 'Making the order',
                        link: '/making-the-order',
                        partOfGrammarId: "dkfj3iusd9f3j",
                        isOpen: true,
                        isStudied: false,
                    },
                    {
                        id: 'sdlfkj23987sd',
                        name: 'Allergies',
                        link: '/allergies',
                        partOfGrammarId: "lkjf02398sdlkj2",
                        isOpen: true,
                        isStudied: false,
                    },
                    {
                        id: 'sdlfkjl23kj',
                        name: 'Paying bills',
                        link: '/paying-bills',
                        partOfGrammarId: "jsdj2987sdhfsjd",
                        isOpen: true,
                        isStudied: false,
                    },
                ]
            },
            {
                id: 'sdlkj23098sd',
                name: 'Renting a car',
                link: '/renting-a-car',
                partOfGrammarId: "dsflkj939898sds",
                isOpen: true,
                isStudied: false,
                isOpenSubThemes: true,
                subThemes: [
                    {
                        id: 'sdlkjf23921',
                        name: 'Insurance',
                        link: '/insurance',
                        partOfGrammarId: "alkj2387fs98d7f",
                        isOpen: true,
                        isStudied: false,
                    },
                    {
                        id: 'dslkfj02938',
                        name: 'Options',
                        link: '/options',
                        partOfGrammarId: "fksj379s8d7j2h",
                        isOpen: true,
                        isStudied: false,
                    },
                ]
            },
        ]
    },
    {
        id: 'sdlkj348203948667',
        userId: 'dfjl3409s9df8hfhf',
        userRoute: [],
    }
]