

export const initialThemes = [
    {
        id: "sdkfjsldfks",
        title: 'all themes',
        description: '',
        test: [],
    },
    {
        id: "fkjrf80s9df83",
        title: 'for all occasions',
        russianTitle: 'Фразы на все случаи жизни',
        theory: 'for_all_occasions.md',
        description: '',
        test: [],
        userId: ['dlkfjl3487f9s', ]
    },
    {
        id: "kjdh087djh387s",
        title: 'for all occasions, part II',
        russianTitle: 'Фразы на все случаи жизни, часть 2',
        theory: 'for_all_occasions_2.md',
        description: '',
        test: [],
    },
    {
        id: "flkj2098srjsl9122",
        title: 'How to be polite (greetings and requests)',
        russianTitle: 'Проявляем вежливость (приветствия и просьбы)',
        theory: 'how_to_be_polite.md',
        description: '',
        test: [],
    },
    {
        id: "flkj2098srdj3ufsdf",
        title: 'How to be polite (advices)',
        russianTitle: 'Проявляем вежливость (советы)',
        theory: 'how_to_be_polite_advices.md',
        description: '',
        test: [],
    },
    {
        id: "dkj2387slaflja",
        title: 'Проясняем непонимание (часть 1)',
        russianTitle: 'Проясняем непонимание (часть 1)',
        theory: 'clarify_possible_misunderstandings_1.md',
        description: '',
        test: [],
    },
    {
        id: "glkjsd93809s8d",
        title: 'Проясняем непонимание (часть 2)',
        russianTitle: 'Проясняем непонимание (часть 2)',
        theory: 'clarify_possible_misunderstandings_2.md',
        description: '',
        test: [],
    },
    {
        id: "lsd879823skjdhf",
        title: 'Small talk',
        russianTitle: 'Смол толк',
        theory: 'small_talk.md',
        description: '',
        test: [],
    },
    {
        id: "fl3ef7j3rfsj3f7s",
        title: 'Вводные фразы (часть 1)',
        russianTitle: 'Вводные фразы (часть 1)',
        theory: 'introductory_phrases_1.md',
        description: '',
        test: [],
    },
    {
        id: "fl3ef7j3rfsj3f7sdj2",
        title: 'Вводные фразы (часть 2)',
        russianTitle: 'Вводные фразы (часть 2)',
        theory: 'introductory_phrases_2.md',
        description: '',
        test: [],
    },
    {
        id: "dkj2398sdkj498sdgf",
        title: 'Вводные фразы (часть 3)',
        russianTitle: 'Вводные фразы (часть 3)',
        theory: 'introductory_phrases_3.md',
        description: '',
        test: [],
    },
    {
        id: "dkj2398sdkj498sdgfajsh",
        title: 'Вводные фразы (часть 4)',
        russianTitle: 'Вводные фразы (часть 4)',
        theory: 'introductory_phrases_4.md',
        description: '',
        test: [],
    },
    {
        id: "lskj98s0dj3ks0d98f",
        title: 'Вводные фразы (часть 5)',
        russianTitle: 'Вводные фразы (часть 5)',
        theory: 'introductory_phrases_5.md',
        description: '',
        test: [],
    },
    {
        id: "lskj98s0dj3ks0d98laksj2",
        title: 'Вводные фразы (часть 6)',
        russianTitle: 'Вводные фразы (часть 6)',
        theory: 'introductory_phrases_6.md',
        description: '',
        test: [],
    },
    {
        id: "jh387fsjh387fsjdhf",
        title: 'Вводные фразы (часть 7)',
        russianTitle: 'Вводные фразы (часть 7)',
        theory: 'introductory_phrases_7.md',
        description: '',
        test: [],
    },
    {
        id: "lsd879dlkj823sk",
        title: 'Restaurants',
        russianTitle: 'В ресторане',
        theory: 'restaurants.md',
        description: '',
        test: [],
    },
    {
        id: "dkfj3iusd9f3j",
        title: 'order at the restaurant',
        description: '',
        test: [],
        russianTitle: 'Делаем заказ в ресторане',
        theory: 'order_at_the_restaurant.md',
        wordsDefinitions: [''],
    },
    {
        id: "lkjf02398sdlkj2",
        title: 'Allergies',
        description: '',
        test: [],
        russianTitle: 'Аллергии, непереносимость продукта',
        theory: 'allergies.md',
        wordsDefinitions: [''],
    },
    {
        id: "jsdj2987sdhfsjd",
        title: 'Paying bills',
        russianTitle: 'Оплачиваем счет',
        theory: 'paying_bills.md',
        description: '',
        test: [],
    },
    {
        id: "dsflkj939898sds",
        title: 'Renting a car',
        russianTitle: 'Арендуем автомобиль',
        theory: 'renting_a_car.md',
        description: '',
        test: [],
    },
    {
        id: "alkj2387fs98d7f",
        title: 'Insurance',
        russianTitle: 'Выбираем страховку авто',
        theory: 'insurance.md',
        description: '',
        test: [],
    },
    {
        id: "fksj379s8d7j2h",
        title: 'Options on renting a car',
        russianTitle: 'Опции при бронировании авто',
        theory: 'options_on_renting_a_car.md',
        description: '',
        test: [],
    },
    // темы без описания - просто для тренировок
    {
        id: "sldkjf34820934",
        title: 'relationships',
        description: '',
        test: [],
        wordsDefinitions: [''],
        
    },
    {
        id: 'lsdkjf203984',
        title: 'travel',
        description: '',
        test: [],
        wordsDefinitions: [''],
        
    },
    {
        id: "lkdjf23948",
        title: 'job',
        description: '',
        test: [],
        wordsDefinitions: [''],
        
    },
    {
        id: 'sldjflkj232342',
        title: 'hotel',
        description: '',
        test: [],
        wordsDefinitions: [''],
        
    },
    {
        id: "slkdjflk34234",
        title: 'family',
        description: '',
        test: [],
        wordsDefinitionsDefinitions: [''],
        
    },
    {
        id: "slkdjf23423",
        title: 'movie',
        description: '',
        test: [],
        wordsDefinitions: [''],
        
    },
    {
        id: "ewir2kj342lkj",
        title: 'friendship',
        description: '',
        test: [],
        wordsDefinitions: [''],
        
    },
    {
        id: "ldkj234jk",
        title: 'dates',
        description: '',
        test: [],
        wordsDefinitions: [''],
        
    },
    {
        id: "lskdjlk2342kj",
        title: 'skin care',
        description: '',
        test: [],
        wordsDefinitions: [''],
        
    },
    {
        id: "flkj3f8s9d83j2",
        title: 'hair care',
        description: '',
        test: [],
        wordsDefinitions: [''],
        
    },
    {
        id: "sldkjf234234",
        title: 'describes',
        description: '',
        test: [],
        wordsDefinitions: [''],
        
    },
    {
        id: "lskdjf23423",
        title: 'transport',
        description: '',
        test: [],
        wordsDefinitions: [''],
        
    },
    {
        id: "lskdjflk3242",
        title: 'asking',
        description: '',
        test: [],
        wordsDefinitions: [''],
        
    },
    {
        id: 'fj234d9fsj3jfsd',
        title: 'making stories',
        description: '',
        test: [],
        wordsDefinitions: [''],
        
    },
    // {
    //     id: uuidv4(),
    //     title: '',
    //     description: '',
    //     test: [],
    //     wordsDefinitions: [''],
    //     
    // },
]