import {v4 as uuidv4} from 'uuid';

export const initialSentences = [
    {
        id: uuidv4(),
        english: 'If I stay here, will you let him go?',
        russian: 'Если я останусь здесь, ты отпустишь его?',
        grammar: ["kjsdf2834792837", 'sdlfkj23498s7f'],
        themes: [],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'Because if you don’t, I’ll divorce you.',
        russian: 'Потому что если ты этого не сделаешь, я с тобой разведусь.',
        grammar: ["kjsdf2834792837", 'sdlfkj23498s7f'],
        themes: ["slkdjflk34234"],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'If you push the button, two things will happen.',
        russian: 'Если вы нажмете кнопку, произойдут две вещи.',
        grammar: ["kjsdf2834792837", 'sdlfkj23498s7f'],
        themes: [],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'I’ll never be the same if we ever meet again.',
        russian: 'Я никогда не буду прежней, если мы когда-нибудь встретимся снова.',
        grammar: ["kjsdf2834792837", 'sdlfkj23498s7f'],
        themes: ["sldkjf34820934s"],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'If that was a movie, I would go see it.',
        russian: 'Если бы это был фильм, я бы сходил на него.',
        grammar: ["lsdjf298374", 'sdlfkj23498s7f'],
        themes: ["slkdjf23423"],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'If you weren’t my friend, there’d be a hole in my life.',
        russian: 'Если бы ты не был моим другом, в моей жизни была бы дыра.',
        grammar: ["lsdjf298374", 'sdlfkj23498s7f'],
        themes: ['conditional 2', "ewir2kj342lkj"],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'Would it be totally weird if I used it?',
        russian: 'Будет очень странно, если я воспользуюсь им?',
        grammar: ["lsdjf298374", 'sdlfkj23498s7f'],
        themes: ['conditional 2',],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'Would you dance if I asked you to dance?',
        russian: 'Ты бы потанцевала со мной, если бы я пригласил тебя на танец?',
        grammar: ["lsdjf298374", 'sdlfkj23498s7f'],
        themes: ['conditional 2', "ldkj234jk"],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'If you gave me a chance, I would take it.',
        russian: 'Если бы ты дал мне шанс, я бы им воспользовалась.',
        grammar: ["lsdjf298374", 'sdlfkj23498s7f'],
        themes: ['conditional 2', "sldkjf34820934s"],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'If you hadn’t been so rude to me, we wouldn’t have argued.',
        russian: 'Если бы ты не был груб со мной, мы бы не поругались.',
        grammar: ["023984lskdjf", 'sdlfkj23498s7f'],
        themes: ["sldkjf34820934s"],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'If I had set up an alarm clock, I wouldn’t have been late.',
        russian: 'Если бы я завел будильник, я бы не опоздал.',
        grammar: ["023984lskdjf", 'sdlfkj23498s7f'],
        themes: [],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'If I had left earlier, I wouldn’t have missed my flight.',
        russian: 'Если бы я выехал раньше, я бы не опоздал на рейс.',
        grammar: ["023984lskdjf", 'sdlfkj23498s7f'],
        themes: ["lsdkjf203984"],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'If she had replied to my message, I wouldn’t have been so worried.',
        russian: 'Если бы она ответила на мое сообщение, я бы так не волновался.',
        grammar: ["023984lskdjf", 'sdlfkj23498s7f'],
        themes: ["sldkjf34820934s"],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'She would have gotten this job, if she had better prepared for the interview.',
        russian: 'Она получила бы эту работу, если бы лучше подготовилась к собеседованию.',
        grammar: ["023984lskdjf", 'sdlfkj23498s7f'],
        themes: ["lkdjf23948"],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'If I had done a bit more research, I would have realized this hotel had terrible reviews.',
        russian: 'Если бы я поискал больше информации, я бы понял, что у этого отеля ужасные отзывы.',
        grammar: ["023984lskdjf", 'sdlfkj23498s7f'],
        themes: ["lsdkjf203984", "sldjflkj232342"],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'I’d like to choose daily skin care.',
        russian: 'Я бы хотела подобрать уход для кожи на каждый день.',
        grammar: [],
        themes: ["lskdjlk2342kj"],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'I prefer more natural products',
        russian: 'Я предпочитаю более натуральные средства',
        grammar: ["sdlkjf3487"],
        themes: ["lskdjlk2342kj"],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'preferably — fragrance-free and odorless',
        russian: 'желательно - без отдушек и запаха',
        grammar: [],
        themes: ["lskdjlk2342kj"],
        partOfSpeech: [],
        words: ['sdlkjo2387skj3', ],
        definition: ['elkrjelr89384eljeru', ],
    },
    {
        id: uuidv4(),
        english: 'I’m looking for an exfoliating mask,',
        russian: 'Я ищу отшелушивающую маску-эксфолиант,',
        grammar: ["flkj2342jh"],
        themes: ["lskdjlk2342kj"],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'to cleanse my skin',
        russian: 'чтобы очищать кожу',
        grammar: [],
        themes: ["lskdjlk2342kj"],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'to eliminating dead cells / to exfoliate dead cells',
        russian: 'чтобы очищать кожу от мертвых клеток,',
        grammar: [],
        themes: ["lskdjlk2342kj"],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'to deeply cleanse the pores',
        russian: 'чтобы глубоко очищать поры',
        grammar: [],
        themes: ["lskdjlk2342kj"],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'to make my skin soft',
        russian: 'чтобы сделать кожу нежной,',
        grammar: [],
        themes: ["lskdjlk2342kj"],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'to make my skin look brighter and healthy',
        russian: 'чтобы делать мою кожу светлее и здоровее',
        grammar: ["flksj38472983"],
        themes: ["lskdjlk2342kj"],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'Will it make my skin look more healthy',
        russian: 'Это сделает кожу более здоровой на вид?',
        grammar: ["flksj38472983"],
        themes: ["lskdjlk2342kj"],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'I’d like a hyaluronic acid serum',
        russian: 'Я бы хотела серум с гиалуроновой кислотой',
        grammar: ["sdlkjf3487"],
        themes: ["lskdjlk2342kj"],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'to moisturize my skin',
        russian: 'чтобы увлажнить кожу',
        grammar: [],
        themes: ["lskdjlk2342kj"],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'As a night or winter cream',
        russian: 'В качестве ночного или зимнего крема',
        grammar: [],
        themes: ["lskdjlk2342kj"],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'I prefer nourishing cream with oils and herbal extracts',
        russian: 'Я предпочитаю питательный крем с маслами и растительными экстрактами',
        grammar: ["sdlkjf3487"],
        themes: ["lskdjlk2342kj"],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'to make my skin more lifted',
        russian: 'чтобы сделать кожу более подтянутой,',
        grammar: [],
        themes: ["lskdjlk2342kj"],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'to reduce fine lines and wrinkles',
        russian: 'чтобы уменьшить мелкие морщинки и складки',
        grammar: [],
        themes: ["lskdjlk2342kj"],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'with natural ingredients, fragrance-free and odorless',
        russian: 'с натуральными ингредиентами, без отдушек и запаха',
        grammar: [],
        themes: ["lskdjlk2342kj"],
        partOfSpeech: [],
        words: ['sdlkjo2387skj3', ],
        definition: ['elkrjelr89384eljeru'],
    },
    {
        id: uuidv4(),
        english: 'I`m looking for a product that will hide existing wrinkles',
        russian: 'Я ищу продукт, который скроет существующие морщинки',
        grammar: ["flkj2342jh"],
        themes: ["lskdjlk2342kj"],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'I`m looking for a product that will prevent new wrinkles from appearing.',
        russian: 'Я ищу продукт, который предотвратить появление новых морщин',
        grammar: ["flkj2342jh"],
        themes: ["lskdjlk2342kj"],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'I`d like to get a pronounced effect of tightening the skin',
        russian: 'Я бы хотела получить выраженный эффект подтяжки кожи',
        grammar: ["sdlkjf3487"],
        themes: ["lskdjlk2342kj"],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'that doesn`t need rinsing out',
        russian: 'который не нужно смывать',
        grammar: [],
        themes: ["lskdjlk2342kj"],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'Micellar Water is also ideal for cleansing your makeup before going to bed.',
        russian: 'Также мицеллярная вода идеально подходит для снятия макияжа перед сном.',
        grammar: [],
        themes: ["lskdjlk2342kj"],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'for smoothing out existing wrinkles',
        russian: 'для разглаживания существующих морщин ',
        grammar: [],
        themes: ["lskdjlk2342kj"],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'to reduce wrinkles, lighten and smooth the skin',
        russian: 'чтобы уменьшать морщины, осветлять и разглаживать кожу',
        grammar: [],
        themes: ["lskdjlk2342kj"],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'to reduce blemishes, wrinkles and other signs of aging',
        russian: 'чтобы уменьшить пятна, морщины и другие признаков старения',
        grammar: [],
        themes: ["lskdjlk2342kj"],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'Revitalizing Serum is a rich serum with a light texture',
        russian: 'Серум для восстановления кожи - это обогащенный серум, обладающий легкой текстурой.',
        grammar: [],
        themes: ["lskdjlk2342kj"],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'Anti-hair loss serum',
        russian: 'Серум против выпадения волос',
        grammar: [],
        themes: ["flkj3f8s9d83j2"],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'it repairs the structure of the hair`s keratin intensely and protects it',
        russian: 'он интенсивно восстанавливает структуру кератина волос и защищает его',
        grammar: [],
        themes: ["flkj3f8s9d83j2"],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'giving extreme shine, softness and vitality',
        russian: 'придавая экстремальный блеск, мягкость и жизненную силу',
        grammar: [],
        themes: ["flkj3f8s9d83j2"],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'it prevents frizzy hair',
        russian: 'Он предотвращает вьющиеся волосы (не дает волосам сильно виться)',
        grammar: [],
        themes: ["flkj3f8s9d83j2"],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'is a spray to seal the hair structure',
        russian: 'спрей для уплотнения структуры волос',
        grammar: [],
        themes: ["flkj3f8s9d83j2"],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'Use a heat protectant spray before curling your hair to prevent losing the curl pattern - that`s what the heat protectant is for',
        russian: 'Используйте термозащитный спрес перед завивкой волос, чтобы предотвратить потерю локонов - это то, зачем нужна термозащита',
        grammar: [],
        themes: ["flkj3f8s9d83j2"],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'Our local shop has very convenient opening hours.',
        russian: 'У нашего местного магазина очень удобные часы работы.',
        grammar: ["sdlkjf3487"],
        themes: ["sldkjf234234"],
        partOfSpeech: ["sldkjf230498"],
        words: ['2l3kj4l2k3lkj2lk3j4l'],
        definition: ['sjkh3fhsk7293847293'],
    },
    {
        id: uuidv4(),
        english: 'Sorry for the inconvenience.',
        russian: 'Извините за неудобства.',
        grammar: ["sdlkjf3487"],
        themes: ["sldkjf234234"],
        partOfSpeech: ["sldkjf230498"],
        words: ['2l3kj4l2k3lkj2lk3j4l'],
        definition: ['sjkh3fhsk7293847293'],
    },
    {
        id: uuidv4(),
        english: 'A bike`s a very convenient way of getting around.',
        russian: 'Велосипед - очень удобный способ передвижения.',
        grammar: ["sdlkjf3487"],
        themes: ["sldkjf234234"],
        partOfSpeech: ["sldkjf230498"],
        words: ['2l3kj4l2k3lkj2lk3j4l'],
        definition: ['sjkh3fhsk7293847293'],
    },
    {
        id: uuidv4(),
        english: 'What time would it be convenient for me to come over?',
        russian: 'Во сколько мне будет удобно приехать?',
        grammar: [],
        themes: ['sldkjf34820934s'],
        partOfSpeech: ["sldkjf230498"],
        words: ['2l3kj4l2k3lkj2lk3j4l'],
        definition: ['sjkh3fhsk7293847293'],
    },
    {
        id: uuidv4(),
        english: 'It`s not really convenient for you to come this afternoon.',
        russian: 'Тебе не очень удобно приходить сегодня днем.',
        grammar: ["sdlkjf3487"],
        themes: ['sldkjf34820934s'],
        partOfSpeech: ["sldkjf230498"],
        words: ['2l3kj4l2k3lkj2lk3j4l'],
        definition: ['sjkh3fhsk7293847293'],
    },
    {
        id: uuidv4(),
        english: 'Would 3 o’clock be a convenient time to meet?',
        russian: 'З часа — удобное время для встречи?',
        grammar: [],
        themes: ['sldkjf34820934s'],
        partOfSpeech: ["sldkjf230498"],
        words: ['2l3kj4l2k3lkj2lk3j4l'],
        definition: ['sjkh3fhsk7293847293'],
    },
    {
        id: uuidv4(),
        english: 'a very convenient bus service',
        russian: 'очень удобное автобусное обслуживание',
        grammar: [],
        themes: ["lskdjf23423"],
        partOfSpeech: ["sldkjf230498"],
        words: ["2l3kj4l2k3lkj2lk3j4l"],
        definition: ['jksfhk34hj43234234hh4'],
    },
    {
        id: uuidv4(),
        english: 'Our new house is very convenient for the kids school.',
        russian: 'Наш новый дом очень удобен — он рядом со школой детей.',
        grammar: ["sdlkjf3487"],
        themes: ["sldkjf234234"],
        partOfSpeech: ["sldkjf230498"],
        words: ["2l3kj4l2k3lkj2lk3j4l"],
        definition: ['jksfhk34hj43234234hh4'],
    },
    {
        id: uuidv4(),
        english: 'Everything is convenient and reliable here.',
        russian: 'Здесь все очень удобно и надежно настроено.',
        grammar: ["sdlkjf3487"],
        themes: ["sldkjf234234"],
        partOfSpeech: ["sldkjf230498"],
        words: ["2l3kj4l2k3lkj2lk3j4l"],
        definition: ['sjkh3fhsk7293847293'],
    },
    {
        id: uuidv4(),
        english: 'This design is convenient for both women and men.',
        russian: 'Этот дизайн удобен как для женщин, так и для мужчин.',
        grammar: ["sdlkjf3487"],
        themes: ["sldkjf234234"],
        partOfSpeech: ["sldkjf230498"],
        words: ['2l3kj4l2k3lkj2lk3j4l'],
        definition: ['sjkh3fhsk7293847293'],
    },
    {
        id: uuidv4(),
        english: 'It is convenient to shops and the beach.',
        russian: 'Очень удобно расположен по отношению к магазинам и пляжу.',
        grammar: ["sdlkjf3487"],
        themes: ["sldkjf234234"],
        partOfSpeech: ["sldkjf230498"],
        words: ['2l3kj4l2k3lkj2lk3j4l'],
        definition: ['jksfhk34hj43234234hh4'],
    },
    {
        id: uuidv4(),
        english: 'Near the hotel: cafes, shops, market; convenient transport interchange.',
        russian: 'Рядом с отелем: кафе, магазины, рынок; удобная транспортная развязка.',
        grammar: [],
        themes: ["sldkjf234234"],
        partOfSpeech: ["sldkjf230498"],
        words: ['2l3kj4l2k3lkj2lk3j4l'],
        definition: ['jksfhk34hj43234234hh4'],
    },
    {
        id: uuidv4(),
        english: 'There are lots of shops around there and it was very convenient.',
        russian: 'Поблизости было много магазинов, что очень удобно.',
        grammar: ["sdlkjf3487"],
        themes: ["sldkjf234234"],
        partOfSpeech: ["sldkjf230498"],
        words: ['2l3kj4l2k3lkj2lk3j4l'],
        definition: ['jksfhk34hj43234234hh4'],
    },
    {
        id: uuidv4(),
        english: 'I watched the interview and felt he came over as quite arrogant.',
        russian: 'Я смотрел интервью и чувствовал, что он относится к высокомерному типу людей',
        grammar: ["fklj342342kj"],
        themes: ["sldkjf234234"],
        partOfSpeech: ["ksdljf29387"],
        words: ['2lk3j4l2kj34l2hlkj23'],
        definition: ['flskj42347987fsd'],
    },
    {
        id: uuidv4(),
        english: 'I think she comes over as very nervous.',
        russian: 'Я думаю, она относится к тому типу людей, которые очень нервничают',
        grammar: ["sdlkjf3487"],
        themes: ["sldkjf234234"],
        partOfSpeech: ["ksdljf29387"],
        words: ['2lk3j4l2kj34l2hlkj23'],
        definition: ['flskj42347987fsd'],
    },
    {
        id: uuidv4(),
        english: 'Come over here!',
        russian: 'Идите сюда!',
        grammar: ["flkj3423423"],
        themes: ['sldkjf34820934'],
        partOfSpeech: ["ksdljf29387"],
        words: ['2lk3j4l2kj34l2hlkj23',],
        definition: ['slkdfj28374928374'],
    },
    {
        id: uuidv4(),
        english: 'Is your family coming over from Greece for the wedding?',
        russian: 'Твоя семья приедет из Греции на свадьбу?',
        grammar: ["flkj2342jh"],
        themes: ['sldkjf34820934'],
        partOfSpeech: ["ksdljf29387"],
        words: ['2lk3j4l2kj34l2hlkj23',],
        definition: ['slkdfj28374928374'],
    },
    {
        id: uuidv4(),
        english: 'Ron came over for dinner.',
        russian: 'Рон приходил на ужин.',
        grammar: ["fklj342342kj"],
        themes: ['sldkjf34820934'],
        partOfSpeech: ["ksdljf29387"],
        words: ['2lk3j4l2kj34l2hlkj23',],
        definition: ['lfkj2414u12412jjj'],
    },
    {
        id: uuidv4(),
        english: 'I`m sorry! That was a stupid thing to say - I don`t know what came over me.',
        russian: 'Прости! Это было глупо - я не знаю, что на меня нашло.',
        grammar: ["fklj342342kj"],
        themes: ['sldkjf34820934'],
        partOfSpeech: ["ksdljf29387"],
        words: ['sdfkjl23k4jl23j4'],
        definition: ['sldkfj293847fsd'],
    },
    {
        id: uuidv4(),
        english: 'He gave you a present! What`s come over him?',
        russian: 'Он подарил тебе подарок! Что с ним?',
        grammar: ["fklj342342kj"],
        themes: ['sldkjf34820934'],
        partOfSpeech: ["ksdljf29387"],
        words: ['sdfkjl23k4jl23j4'],
        definition: ['sldkfj293847fsd'],
    },
    {
        id: uuidv4(),
        english: 'Would you mind speaking more slowly, please?',
        russian: 'Не могли бы вы говорить помедленнее, пожалуйста?',
        grammar: [],
        themes: ['lskdjflk3242'],
        partOfSpeech: ["s;ldkf2394"],
        words: ['sldkfj02398425kjfs'],
        definition: ['fjlk3523lkj235j23'],
    },
    {
        id: uuidv4(),
        english: 'Can I speak with Scott please?',
        russian: 'Могу я поговорить со Скоттом?',
        grammar: ["sldkfj238975"],
        themes: ['lskdjflk3242'],
        partOfSpeech: ["s;ldkf2394"],
        words: ['sldkfj02398425kjfs'],
        definition: ['fjlk3523lkj235j23'],
    },
    {
        id: uuidv4(),
        english: 'If he tells Julie what I said, I`ll never speak to him again.',
        russian: 'Если он скажет Джули то, что я сказал, я никогда с ним больше не заговорю.',
        grammar: ['kjsdf2834792837'],
        themes: ['sldkjf34820934'],
        partOfSpeech: ["s;ldkf2394"],
        words: ['sldkfj02398425kjfs'],
        definition: ['fjlk3523lkj235j23'],
    },
    {
        id: uuidv4(),
        english: 'She speaks very highly of the new director.',
        russian: 'Она очень высоко отзывается о новом директоре.',
        grammar: ["sdlkjf3487"],
        themes: ['sldkjf34820934'],
        partOfSpeech: ["s;ldkf2394"],
        words: ['sldkfj02398425kjfs'],
        definition: ['fjlk3523lkj235j23'],
    },
    {
        id: uuidv4(),
        english: 'I can certainly come but I can`t speak for my wife',
        russian: 'Я, конечно, могу прийти, но не могу говорить за свою жену.',
        grammar: ['sldkfj238975'],
        themes: ['sldkjf34820934'],
        partOfSpeech: ["s;ldkf2394"],
        words: ['sldkfj02398425kjfs'],
        definition: ['fjlk3523lkj235j23'],
    },
    {
        id: uuidv4(),
        english: 'He`s old enough to speak for himself.',
        russian: 'Он достаточно взрослый, чтобы говорить за себя.',
        grammar: ['sdlkjf3487'],
        themes: ['sldkjf34820934'],
        partOfSpeech: ["s;ldkf2394"],
        words: ['sldkfj02398425kjfs'],
        definition: ['fjlk3523lkj235j23'],
    },
    {
        id: uuidv4(),
        english: 'Speaking as a mother of four, I can tell you that children are exhausting.',
        russian: 'Говоря как мама четырех, я могу сказать вам, что дети изнурительны.',
        grammar: ['sldkfj238975'],
        themes: ['sldkjf34820934'],
        partOfSpeech: ["s;ldkf2394"],
        words: ['sldkfj02398425kjfs'],
        definition: ['fjlk3523lkj235j23'],
    },
    {
        id: uuidv4(),
        english: 'We`ve been invited to Rachel and Jamie`s wedding - speaking of which, did you know that they`re moving to New York?',
        russian: 'Нас пригласили на свадьбу Рейчел и Джейми, кстати говоря, ты знала, что они переезжают в Нью-Йорк?',
        grammar: ['slkj234234'],
        themes: ['ewir2kj342lkj'],
        partOfSpeech: ["s;ldkf2394"],
        words: ['sldkfj02398425kjfs'],
        definition: ['fjlk3523lkj235j23'],
    },
    {
        id: uuidv4(),
        english: 'Sue speaks with an American accent.',
        russian: 'Сью говорит с американским акцентом.',
        grammar: ['sdlkjf3487'],
        themes: [''],
        partOfSpeech: ["s;ldkf2394"],
        words: ['sldkfj02398425kjfs'],
        definition: ['fjlk3523lkj235j23'],
    },
    {
        id: uuidv4(),
        english: 'Why are you speaking in a whisper?',
        russian: 'Почему ты говоришь шепотом?',
        grammar: ['flkj2342jh'],
        themes: ['sldkjf34820934'],
        partOfSpeech: ["s;ldkf2394"],
        words: ['sldkfj02398425kjfs'],
        definition: ['fjlk3523lkj235j23'],
    },
    {
        id: uuidv4(),
        english: 'For five whole minutes, neither of them spoke a word.',
        russian: 'Целых пять минут ни один из них не говорил ни слова.',
        grammar: ['fklj342342kj'],
        themes: ['sldkjf34820934'],
        partOfSpeech: ["s;ldkf2394"],
        words: ['sldkfj02398425kjfs'],
        definition: ['fjlk3523lkj235j23'],
    },
    {
        id: uuidv4(),
        english: 'Could I speak to you privately?',
        russian: 'Могу я поговорить с вами наедине?',
        grammar: ['sldkfj238975'],
        themes: ['sldkjf34820934'],
        partOfSpeech: ["s;ldkf2394"],
        words: ['sldkfj02398425kjfs'],
        definition: ['fjlk3523lkj235j23'],
    },
    {
        id: uuidv4(),
        english: 'When last we spoke, you said you needed time.',
        russian: 'Когда мы говорили последний раз, ты говорила, что тебе нужно время.',
        grammar: ['fklj342342kj'],
        themes: ['sldkjf34820934'],
        partOfSpeech: ["s;ldkf2394"],
        words: ['sldkfj02398425kjfs'],
        definition: ['fjlk3523lkj235j23'],
    },
    {
        id: uuidv4(),
        english: 'He also spoke at the briefing.',
        russian: 'Во время брифинга он также выступил с речью.',
        grammar: ['fklj342342kj'],
        themes: ['sldkjf34820934'],
        partOfSpeech: ["s;ldkf2394"],
        words: ['sldkfj02398425kjfs'],
        definition: ['fjlk3523lkj235j23'],
    },
    {
        id: uuidv4(),
        english: 'Yes, I have spoken to him.',
        russian: 'Да, я говорил с ним.',
        grammar: ['slkj234234'],
        themes: ['sldkjf34820934'],
        partOfSpeech: ["s;ldkf2394"],
        words: ['sldkfj02398425kjfs'],
        definition: ['fjlk3523lkj235j23'],
    },
    {
        id: uuidv4(),
        english: ' Maybe, we should have spoken before this.',
        russian: 'Можно сказать, что мы должны были поговорить об этом раньше.',
        grammar: ['slkj234234'],
        themes: ['sldkjf34820934'],
        partOfSpeech: ["s;ldkf2394"],
        words: ['sldkfj02398425kjfs'],
        definition: ['fjlk3523lkj235j23'],
    },
    {
        id: uuidv4(),
        english: ' I think I have spoken enough about it.',
        russian: 'Я думаю, мы сказали достаточно по этому вопросу.',
        grammar: ['slkj234234'],
        themes: ['sldkjf34820934'],
        partOfSpeech: ["s;ldkf2394"],
        words: ['sldkfj02398425kjfs'],
        definition: ['fjlk3523lkj235j23'],
    },
    {
        id: uuidv4(),
        english: 'I have spoken about my experience previously.',
        russian: 'Я рассказала о своем опыте прежде.',
        grammar: ['slkj234234'],
        themes: ['sldkjf34820934'],
        partOfSpeech: ["s;ldkf2394"],
        words: ['sldkfj02398425kjfs'],
        definition: ['fjlk3523lkj235j23'],
    },

    {
        id: uuidv4(),
        english: 'I`d like to share with you guys, how beautiful it is here',
        russian: 'хочу поделиться с вами, как здесь красиво',
        grammar: [],
        themes: ['fj234d9fsj3jfsd'],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'This is ancient Greek civilization',
        russian: 'Это древняя греческая цивилизация',
        grammar: [],
        themes: ['fj234d9fsj3jfsd'],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'It was built before our era, more than 2000 years ago',
        russian: 'Это было построено до нашей эры, более 2000 лет назад',
        grammar: [],
        themes: ['fj234d9fsj3jfsd'],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'I finally got my favorite cappuccino at Starbucks',
        russian: 'я, наконец, получила мой любимый капучино в старбаксе,',
        grammar: [],
        themes: ['fj234d9fsj3jfsd'],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'we were here in January, and since then I’ve been dreaming about this pistachio ice cream',
        russian: 'мы были здесь в январе, и с тех пор я мечтала об этом фисташковом мороженом',
        grammar: [],
        themes: ['fj234d9fsj3jfsd'],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'This place here is called Delphi',
        russian: 'Это место называется Дельфы',
        grammar: [],
        themes: ['fj234d9fsj3jfsd'],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'I got up at five o`clock this morning!',
        russian: 'Я сегодня встал в 5 утра.',
        grammar: [],
        themes: [''],
        partOfSpeech: ['ksdljf29387'],
        words: ['sdkfjl348203948skdf', ],
        definition: ['dlkfj2398fdslkj398', ],
    },
    {
        id: uuidv4(),
        english: 'It`s so hard getting the kids up on school days.',
        russian: 'Это трудно — поднять детей в школу.',
        grammar: [],
        themes: [''],
        partOfSpeech: ['ksdljf29387'],
        words: ['sdkfjl348203948skdf', ],
        definition: ['dlkfj2398fdslkj398', ],
    },
    {
        id: uuidv4(),
        english: 'What time do you get up in the morning?',
        russian: 'Когда ты просыпаешься?',
        grammar: [],
        themes: [''],
        partOfSpeech: ['ksdljf29387'],
        words: ['sdkfjl348203948skdf', ],
        definition: ['dlkfj2398fdslkj398', ],
    },
    {
        id: uuidv4(),
        english: 'Helen was in a bad mood when she got up.',
        russian: 'Хелен проснулась в плохом настроении.',
        grammar: [],
        themes: [''],
        partOfSpeech: ['ksdljf29387'],
        words: ['sdkfjl348203948skdf', ],
        definition: ['dlkfj2398fdslkj398', ],
    },
    {
        id: uuidv4(),
        english: 'Simon gets up at six every morning.',
        russian: 'Саймон встает в 6 утра каждое утро.',
        grammar: [],
        themes: [''],
        partOfSpeech: ['ksdljf29387'],
        words: ['sdkfjl348203948skdf', ],
        definition: ['dlkfj2398fdslkj398', ],
    },
    {
        id: uuidv4(),
        english: 'Teach your kids to make their bed as soon as they wake up.',
        russian: 'Приучите детей заправлять кровать сразу после того, как они встанут.',
        grammar: [],
        themes: [''],
        partOfSpeech: ['ksdljf29387'],
        words: ['sdkfjl348203948skdf', ],
        definition: ['dlkfj2398fdslkj398', ],
    },
    {
        id: uuidv4(),
        english: 'I tried his home number but he didn`t pick up.',
        russian: 'Я звонила ему домой, но он не ответил.',
        grammar: [],
        themes: [''],
        partOfSpeech: ['ksdljf29387'],
        words: ['dfgj239r7sdfj237f', ],
        definition: ['dfjk2398sdfkj398f', ],
    },
    {
        id: uuidv4(),
        english: 'Just pick up the phone and call him.',
        russian: 'Возьми трубку и набери его номер.',
        grammar: [],
        themes: [''],
        partOfSpeech: ['ksdljf29387'],
        words: ['dfgj239r7sdfj237f', ],
        definition: ['dfjk2398sdfkj398f', ],
    },
    {
        id: uuidv4(),
        english: 'So don`t ever hesitate to pick up the phone.',
        russian: 'Поэтому никогда не стесняйся взять и позвонить нам.',
        grammar: [],
        themes: [''],
        partOfSpeech: ['ksdljf29387'],
        words: ['dfgj239r7sdfj237f', ],
        definition: ['dfjk2398sdfkj398f', ],
    },
    {
        id: uuidv4(),
        english: 'Just pick up the phone and start the new chapter to your life.',
        russian: 'Возьмите телефон и начните новую главу в своей жизни.',
        grammar: [],
        themes: [''],
        partOfSpeech: ['ksdljf29387'],
        words: ['dfgj239r7sdfj237f', ],
        definition: ['dfjk2398sdfkj398f', ],
    },
    {
        id: uuidv4(),
        english: 'You`ve just got to pick up the phone, and you ask him out for dinner.',
        russian: 'Нужно только поднять трубку и пригласить его на ужин.',
        grammar: [],
        themes: [''],
        partOfSpeech: ['ksdljf29387'],
        words: ['dfgj239r7sdfj237f', ],
        definition: ['dfjk2398sdfkj398f', ],
    },
    {
        id: uuidv4(),
        english: 'I couldn`t pick up the phone.',
        russian: 'Я не могла подойти к телефону.',
        grammar: [],
        themes: [''],
        partOfSpeech: ['ksdljf29387'],
        words: ['dfgj239r7sdfj237f', ],
        definition: ['dfjk2398sdfkj398f', ],
    },
    {
        id: uuidv4(),
        english: 'How did you find out about the party?',
        russian: 'Как ты узнал о вечеринке?',
        grammar: ['dlfkj234jlkj34'],
        themes: [''],
        partOfSpeech: ['ksdljf29387'],
        words: ['sdfj3098fsdkj235', ],
        definition: ['sdfdl348f7sjh34kjhsd', ],
    },
    {
        id: uuidv4(),
        english: 'I only found out about it the day before we left.',
        russian: 'Я узнал об этом только за день до нашего отъезда.',
        grammar: [''],
        themes: [''],
        partOfSpeech: ['ksdljf29387'],
        words: ['sdfj3098fsdkj235', ],
        definition: ['sdfdl348f7sjh34kjhsd', ],
    },
    {
        id: uuidv4(),
        english: 'I`ll just go and find out what`s going on outside.',
        russian: 'Я просто пойду и узнаю, что происходит снаружи.',
        grammar: [''],
        themes: [''],
        partOfSpeech: ['ksdljf29387'],
        words: ['sdfj3098fsdkj235', ],
        definition: ['sdfdl348f7sjh34kjhsd', ],
    },
    {
        id: uuidv4(),
        english: 'Look, just go find out what`s going on.',
        russian: 'Слушайте, только схожу узнаю что к чему (что происходит).',
        grammar: [''],
        themes: [''],
        partOfSpeech: ['ksdljf29387'],
        words: ['sdfj3098fsdkj235', ],
        definition: ['sdfdl348f7sjh34kjhsd', ],
    },
    {
        id: uuidv4(),
        english: 'Too late, she found out that the flight had been cancelled.',
        russian: 'Слишком поздно она узнала, что рейс отменили.',
        grammar: [''],
        themes: [''],
        partOfSpeech: ['ksdljf29387'],
        words: ['sdfj3098fsdkj235', ],
        definition: ['sdfdl348f7sjh34kjhsd', ],
    },
    {
        id: uuidv4(),
        english: 'When he found out what we`d done he was so shocked.',
        russian: 'Когда он узнал, что мы сделали, он был так шокирован.',
        grammar: [''],
        themes: [''],
        partOfSpeech: ['ksdljf29387'],
        words: ['sdfj3098fsdkj235', ],
        definition: ['sdfdl348f7sjh34kjhsd', ],
    },
    {
        id: uuidv4(),
        english: 'I must find out how much it will cost.',
        russian: 'Я должен выяснить, сколько это будет стоить.',
        grammar: [''],
        themes: [''],
        partOfSpeech: ['ksdljf29387'],
        words: ['sdfj3098fsdkj235', ],
        definition: ['sdfdl348f7sjh34kjhsd', ],
    },
    {
        id: uuidv4(),
        english: 'While you’re in town, would you pick up a book for me?',
        russian: 'Пока ты в городе, не мог бы ты взять книгу для меня?',
        grammar: [],
        themes: [''],
        partOfSpeech: ['ksdljf29387'],
        words: ['dfgj239r7sdfj237f', ],
        definition: ['fjkj3487f9shk3jr7sd', ],
    },
    {
        id: uuidv4(),
        english: 'to use these to pick up cash from ATMs',
        russian: 'использовать их для получения наличных денег в банкоматах',
        grammar: [],
        themes: [''],
        partOfSpeech: ['ksdljf29387'],
        words: ['dfgj239r7sdfj237f', ],
        definition: ['fjl23kjf8se9df83hfslkd', ],
    },
    {
        id: uuidv4(),
        english: 'pick up cash in the bank',
        russian: 'забрать наличные в кассе банка ',
        grammar: [],
        themes: [''],
        partOfSpeech: ['ksdljf29387'],
        words: ['dfgj239r7sdfj237f', ],
        definition: ['fjl23kjf8se9df83hfslkd', ],
    },
    {
        id: uuidv4(),
        english: 'I need to pick up some cash.',
        russian: 'Мне нужно снять наличные.',
        grammar: ['sdflkj234867s9d8'],
        themes: [''],
        partOfSpeech: ['ksdljf29387'],
        words: ['dfgj239r7sdfj237f', ],
        definition: ['fjl23kjf8se9df83hfslkd', ],
    },
    {
        id: uuidv4(),
        english: 'I picked up an evening paper on the way home.',
        russian: 'Я взял вечернюю газету по дороге домой.',
        grammar: [],
        themes: [''],
        partOfSpeech: ['ksdljf29387'],
        words: ['dfgj239r7sdfj237f', ],
        definition: ['fjl23kjf8se9df83hfslkd', ],
    },
    {
        id: uuidv4(),
        english: 'He’s already picked up three major prizes this year.',
        russian: 'Он уже получил три главных приза в этом году.',
        grammar: ['slkj234234', 'sldkfj3247987'],
        themes: [''],
        partOfSpeech: ['ksdljf29387'],
        words: ['dfgj239r7sdfj237f', ],
        definition: ['fjl23kjf8se9df83hfslkd', ],
    },
    {
        id: uuidv4(),
        english: ' I picked up an evening paper on the way home.',
        russian: 'Я взял вечернюю газету по дороге домой.',
        grammar: [],
        themes: [''],
        partOfSpeech: ['ksdljf29387'],
        words: ['dfgj239r7sdfj237f', ],
        definition: ['fjl23kjf8se9df83hfslkd', ],
    },
    {
        id: uuidv4(),
        english: ' I could schedule the bellboy to pick up your luggage and deliver to the lobby no later than 2:20',
        russian: 'Я могла бы назначить швейцара забрать ваш багаж и принести его в лобби не позднее 2.20',
        grammar: [],
        themes: [''],
        partOfSpeech: ['ksdljf29387'],
        words: ['dfgj239r7sdfj237f', ],
        definition: ['fjkj3487f9shk3jr7sd', ],
    },
    {
        id: uuidv4(),
        english: 'I’m just rushing over to the school to pick up John and Rosie',
        russian: 'я просто спешу в школу, чтобы забрать Джона и Рози',
        grammar: [],
        themes: [''],
        partOfSpeech: ['ksdljf29387'],
        words: ['dfgj239r7sdfj237f', ],
        definition: ['fjkj3487f9shk3jr7sd', ],
    },
    {
        id: uuidv4(),
        english: 'I was wondering, for the ribeye steak, if it would be possible to substitute a salad for the mashed potatoes.',
        russian: 'Хотела узнать, про Рибай стейк, можно заменить салат на пюре.',
        grammar: [''],
        themes: ['dkfj3iusd9f3j'],
        partOfSpeech: [''],
        words: ['elkrjelr89384eljeru', ],
        definition: ['elkrjelr89384eljeru',],
        expressions: ['lkj3erf098sk3', ]
    },
    {
        id: uuidv4(),
        english: 'Then I think we’ll start with the shrimp scampi appetizer, and both share the ribeye steak.',
        russian: 'В таком случае, думаю, мы начнем с креветок в кляре, и также будем Рибай стейк на двоих.',
        grammar: [''],
        themes: ['dkfj3iusd9f3j'],
        partOfSpeech: [''],
        words: ['', ],
        definition: ['',],
        expressions: ['', ]
    },
    {
        id: uuidv4(),
        english: 'Here are your drinks; water for both, with lemon.',
        russian: 'Вот ваши напитки: вода с лимоном.',
        grammar: [''],
        themes: ['dkfj3iusd9f3j'],
        partOfSpeech: [''],
        words: ['', ],
        definition: ['',],
        expressions: ['', ]
    },
    {
        id: uuidv4(),
        english: 'Do you have any questions about the menu?',
        russian: 'У вас есть вопросы по меню?',
        grammar: ['sdflkj234867s9d8'],
        themes: ['dkfj3iusd9f3j'],
        partOfSpeech: [''],
        words: ['', ],
        definition: ['',],
        expressions: ['', ]
    },
    {
        id: uuidv4(),
        english: 'What temperature would you like your steak cooked?',
        russian: 'Какой прожарки хотите мясо?',
        grammar: [''],
        themes: ['dkfj3iusd9f3j'],
        partOfSpeech: [''],
        words: ['', ],
        definition: ['',],
        expressions: ['', ]
    },
    {
        id: uuidv4(),
        english: 'I’m not really sure… do you have a recommendation?',
        russian: 'Не уверена… Что рекомендуете?',
        grammar: ['sdflkj234867s9d8'],
        themes: ['dkfj3iusd9f3j'],
        partOfSpeech: [''],
        words: ['', ],
        definition: ['',],
        expressions: ['', ]
    },
    {
        id: uuidv4(),
        english: 'The chef recommends that the ribeye be cooked medium rare…',
        russian: 'Шеф рекомендует стейк мидиум рэа (слабой прожарки)',
        grammar: ['sdflkj234867s9d8'],
        themes: ['dkfj3iusd9f3j'],
        partOfSpeech: [''],
        words: ['', ],
        definition: ['',],
        expressions: ['', ]
    },
    {
        id: uuidv4(),
        english: 'That sounds great.',
        russian: 'Отлично! (Звучит отлично!)',
        grammar: ['sdflkj234867s9d8'],
        themes: ['dkfj3iusd9f3j', 'fkjrf80s9df83'],
        partOfSpeech: [''],
        words: ['', ],
        definition: ['',],
        expressions: ['', ]
    },
    {
        id: uuidv4(),
        english: 'We’d also like to order a bottle of red wine with the steak. Can you help us choose?',
        russian: 'Мы также хотим заказать бутылку красного вина со стейком. Поможете выбрать?',
        grammar: [''],
        themes: ['dkfj3iusd9f3j',],
        partOfSpeech: [''],
        words: ['', ],
        definition: ['',],
        expressions: ['', ]
    },
    {
        id: uuidv4(),
        english: 'I think this California cabernet blend would work very well with the steak – it’s full bodied, balanced, with hints of cherry and oak.',
        russian: 'Думаю, к стейку отлично подойдет калифорнийское каберне. У него насыщенный вкус, сбалансированный, с нотками вишни и дуба',
        grammar: [''],
        themes: ['dkfj3iusd9f3j',],
        partOfSpeech: [''],
        words: ['', ],
        definition: ['',],
        expressions: ['', ]
    },
    {
        id: uuidv4(),
        english: 'Sounds delicious – we’d love to try that!',
        russian: 'Звучит аппетитно! Мы бы попробовали',
        grammar: [''],
        themes: ['dkfj3iusd9f3j',],
        partOfSpeech: [''],
        words: ['', ],
        definition: ['',],
        expressions: ['', ]
    },
    {
        id: uuidv4(),
        english: 'I don`t drink ordinary milk as I have a lactose intolerance',
        russian: 'Я не пью обычное молоко, так как у меня непереносимость лактозы',
        grammar: [''],
        themes: ['dkfj3iusd9f3j'],
        partOfSpeech: [''],
        words: ['sdfjk2398fsdjf37fajs', ],
        definition: ['elkrjelr89384eljeru',],
        expressions: ['', ]
    },
    {
        id: uuidv4(),
        english: 'We can offer greek yogurt as a substitution for mayonnaise',
        russian: 'Мы можем предложить греческий йогурт как замену майонезу',
        grammar: [''],
        themes: ['dkfj3iusd9f3j'],
        partOfSpeech: [''],
        words: ['sdflkj2398fsdkj23', ],
        definition: ['elkrjelr89384eljeru',],
        expressions: ['', ]
    },
    {
        id: uuidv4(),
        english: 'I have an allergy to cow`s milk, do you have coconut or almond milk?',
        russian: 'У меня аллергия на коровье молоко, у вас есть кососовое или миндальное молоко?',
        grammar: [''],
        themes: ['dkfj3iusd9f3j'],
        partOfSpeech: [''],
        words: ['', ],
        definition: ['',],
        expressions: ['', ]
    },
    {
        id: uuidv4(),
        english: 'May I ask if you have sensitivity to cheese to, or just milk?',
        russian: 'Могу я спросить, у вас также аллергия на сыр, или только на молоко?',
        grammar: [''],
        themes: ['dkfj3iusd9f3j'],
        partOfSpeech: [''],
        words: ['xlkjw098slakdgf', ],
        definition: ['sdflkj398s0d98j3',],
        expressions: ['', ]
    },
    {
        id: uuidv4(),
        english: 'I was also hoping that you could recommend something nice to eat takeaway?',
        russian: 'Я хотела спросить, не порекомендуете что-то вкусное на вынос (с собой)?',
        grammar: [''],
        themes: ['dkfj3iusd9f3j'],
        partOfSpeech: [''],
        words: ['dkjhw987dsjhske', ],
        definition: ['sdflkj398s0d98j3',],
        expressions: ['', ]
    },
    {
        id: uuidv4(),
        english: 'Would you like your coffee with your meal, or right away?',
        russian: 'Вы хотите кофе вместе с едой или прямо сейчас?',
        grammar: [''],
        themes: ['dkfj3iusd9f3j'],
        partOfSpeech: [''],
        words: ['', ],
        definition: ['',],
        expressions: ['', ]
    },
    {
        id: uuidv4(),
        english: 'Then I`l take the gluten-free pancakes option, please.',
        russian: 'В таком случае я бы хотел безглютеновые блинчики, пожалуйста.',
        grammar: [''],
        themes: ['dkfj3iusd9f3j'],
        partOfSpeech: [''],
        words: ['sdlkjo2387skj3', 'sdflkj2098sdkj2h', ],
        definition: ['elkrjelr89384eljeru', 'sdflkj398s0d98j3', ],
        expressions: ['', ]
    },
    {
        id: uuidv4(),
        english: 'I`d like the lactose-free latte option.',
        russian: 'Я бы хотела латте на безлактозном молоке.',
        grammar: [''],
        themes: ['dkfj3iusd9f3j'],
        partOfSpeech: [''],
        words: ['sdlkjo2387skj3', 'sdflkj2098sdkj2h', ],
        definition: ['elkrjelr89384eljeru', 'sdflkj398s0d98j3'],
        expressions: ['', ]
    },
    {
        id: uuidv4(),
        english: 'I`l have the dairy-free milkshake option.',
        russian: 'Я бы хотела молочный коктейль без содержания молока.',
        grammar: [''],
        themes: ['dkfj3iusd9f3j'],
        partOfSpeech: [''],
        words: ['sdlkjo2387skj3', 'sdflkj2098sdkj2h', ],
        definition: ['elkrjelr89384eljeru', 'sdflkj398s0d98j3'],
        expressions: ['', ]
    },
    {
        id: uuidv4(),
        english: 'Excuse me, could I ask you a question?',
        russian: 'Извините, могу я задать вопрос?',
        grammar: [''],
        themes: ['dkfj3iusd9f3j', 'fkjrf80s9df83'],
        partOfSpeech: [''],
        words: ['', ],
        definition: ['',],
        expressions: ['', ]
    },
    {
        id: uuidv4(),
        english: 'Chicory is a good coffee substitution.',
        russian: 'Цикорий - хорошая замена кофе.',
        grammar: [''],
        themes: ['dkfj3iusd9f3j', 'fkjrf80s9df83'],
        partOfSpeech: [''],
        words: ['', ],
        definition: ['',],
        expressions: ['', ]
    },
    {
        id: uuidv4(),
        english: 'Are you ready to order your meal? / Are you ready to order?',
        russian: 'Вы готовы сделать заказ?',
        grammar: [''],
        themes: ['dkfj3iusd9f3j'],
        partOfSpeech: [''],
        words: ['', ],
        definition: ['',],
        expressions: ['', ]
    },
    {
        id: uuidv4(),
        english: 'Yes, but I have a few questions',
        russian: 'Да, но сначала у меня есть несколько вопросов',
        grammar: [''],
        themes: ['dkfj3iusd9f3j'],
        partOfSpeech: [''],
        words: ['', ],
        definition: ['',],
        expressions: ['', ]
    },
    {
        id: uuidv4(),
        english: 'Could I ask a few questions? Yes, of course, please, go ahead.',
        russian: 'Могу я задать пару вопросов? Да, конечно, задавайте',
        grammar: [''],
        themes: ['dkfj3iusd9f3j'],
        partOfSpeech: [''],
        words: ['', ],
        definition: ['',],
        expressions: ['', ]
    },
    {
        id: uuidv4(),
        english: 'I have a gluten intolerance.',
        russian: 'У меня непереносимость глютена',
        grammar: [''],
        themes: ['dkfj3iusd9f3j'],
        partOfSpeech: [''],
        words: ['sdfjk2398fsdjf37fajs', ],
        definition: ['elkrjelr89384eljeru',],
        expressions: ['', ]
    },
    {
        id: uuidv4(),
        english: 'Do you offer gluten-free pasta? / Do you have gluten-free pasta?',
        russian: 'Есть ли у вас паста без глютена?',
        grammar: [''],
        themes: ['dkfj3iusd9f3j'],
        partOfSpeech: [''],
        words: ['sdlkjo2387skj3', ],
        definition: ['elkrjelr89384eljeru',],
        expressions: ['', ]
    },
    {
        id: uuidv4(),
        english: 'Yes, actually, we offer a gluten-free, rice-based penne pasta as a substitution with any of our pasta dishes.',
        russian: 'Да, на самом деле, у нас есть безглютеновая паста пенне (перья) на рисовой основе в качестве замены любому из наших блюд из макарон.',
        grammar: [''],
        themes: ['dkfj3iusd9f3j'],
        partOfSpeech: [''],
        words: ['sdlkjo2387skj3', ],
        definition: ['elkrjelr89384eljeru',],
        expressions: ['', ]
    },
    {
        id: uuidv4(),
        english: 'Oh, excellent. That`s great to hear.',
        russian: 'О, отлично. Рада это слышать.',
        grammar: [''],
        themes: ['dkfj3iusd9f3j'],
        partOfSpeech: [''],
        words: ['', ],
        definition: ['',],
        expressions: ['', ]
    },
    {
        id: uuidv4(),
        english: 'I was also hoping that you could recommend one of the salads as a starter?',
        russian: 'Я также хотела попросить, чтобы вы порекомендовали один из салатов в качестве первого блюда',
        grammar: [''],
        themes: ['dkfj3iusd9f3j'],
        partOfSpeech: [''],
        words: ['', ],
        definition: ['',],
        expressions: ['', ]
    },
    {
        id: uuidv4(),
        english: 'I have an allergy to onions.',
        russian: 'У меня аллергия на лук',
        grammar: [''],
        themes: ['dkfj3iusd9f3j'],
        partOfSpeech: [''],
        words: ['', ],
        definition: ['',],
        expressions: ['', ]
    },
    {
        id: uuidv4(),
        english: 'May I ask if you have a sensitivity to garlic too, or just onions?',
        russian: 'Могу я спросить, у вас также есть аллергия на чеснок, или только на лук?',
        grammar: [''],
        themes: ['dkfj3iusd9f3j'],
        partOfSpeech: [''],
        words: ['xlkjw098slakdgf', ],
        definition: ['sdflkj398s0d98j3',],
        expressions: ['', ]
    },
    {
        id: uuidv4(),
        english: 'Ah, no - it`s just onion, thanks',
        russian: 'А, нет - только на лук',
        grammar: [''],
        themes: ['dkfj3iusd9f3j'],
        partOfSpeech: [''],
        words: ['', ],
        definition: ['',],
        expressions: ['', ]
    },
    {
        id: uuidv4(),
        english: 'Of course. Our caprese salad doesn`t have onions... And we can make the house salad without onions as well',
        russian: 'Конечно. В нашем салате капрезе нет лука... Но мы можем приготовить домашний салат без лука.',
        grammar: [''],
        themes: ['dkfj3iusd9f3j'],
        partOfSpeech: [''],
        words: ['', ],
        definition: ['',],
        expressions: ['', ]
    },
    {
        id: uuidv4(),
        english: 'Then, I`ll take a house salad, no onions, with balsamic vinaigrette, and the gluten-free pasta option, please.',
        russian: 'Тогда я возьму домашний салат без лука с бальзамическим соусом и эту пасту без глютена, пожалуйста.',
        grammar: [''],
        themes: ['dkfj3iusd9f3j'],
        partOfSpeech: [''],
        words: ['sdlkjo2387skj3', 'sdflkj2098sdkj2h', ],
        definition: ['elkrjelr89384eljeru', 'sdflkj398s0d98j3'],
        expressions: ['', ]
    },
    {
        id: uuidv4(),
        english: 'A house salad, no onions, and gluten-free penne puttanesca, correct?',
        russian: 'Домашний салат без лука и пенне путтанеска без глютена, правильно?',
        grammar: [''],
        themes: ['dkfj3iusd9f3j'],
        partOfSpeech: [''],
        words: ['sdlkjo2387skj3', ],
        definition: ['elkrjelr89384eljeru',],
        expressions: ['', ]
    },
    {
        id: uuidv4(),
        english: 'Oh, and a glass of chianti and a small bottle of sparkling water, please.',
        russian: 'О, и бокал кьянти и маленькую бутылочку газированной воды, пожалуйста.',
        grammar: [''],
        themes: ['dkfj3iusd9f3j'],
        partOfSpeech: [''],
        words: ['', ],
        definition: ['',],
        expressions: ['', ]
    },
    {
        id: uuidv4(),
        english: 'Would you like your wine with your meal, or right away? Right away, please.',
        russian: 'Вы хотите вино во время еды или прямо сейчас? Прямо сейчас, пожалуйста.',
        grammar: [''],
        themes: ['dkfj3iusd9f3j'],
        partOfSpeech: [''],
        words: ['', ],
        definition: ['',],
        expressions: ['', ]
    },
    {
        id: uuidv4(),
        english: 'I would like to order some wine and a sparkling water as well.',
        russian: 'Еще я бы хотела заказать вина и газированную воду.',
        grammar: [''],
        themes: ['dkfj3iusd9f3j'],
        partOfSpeech: [''],
        words: ['', ],
        definition: ['',],
        expressions: ['', ]
    },


    {
        id: uuidv4(),
        english: 'I have an allergy to onions.',
        russian: 'У меня аллергия на лук.',
        grammar: [''],
        themes: ['lkjf02398sdlkj2'],
        partOfSpeech: [''],
        words: ['', ],
        definition: ['',],
        expressions: ['', ]
    },
    {
        id: uuidv4(),
        english: 'I have a gluten intolerance.',
        russian: 'У меня непереносимость глютена.',
        grammar: [''],
        themes: ['lkjf02398sdlkj2'],
        partOfSpeech: [''],
        words: ['', ],
        definition: ['',],
        expressions: ['', ]
    },
    {
        id: uuidv4(),
        english: 'Do you offer (have) gluten-free pizza?',
        russian: 'У вас есть пицца без глютена?',
        grammar: [''],
        themes: ['lkjf02398sdlkj2'],
        partOfSpeech: [''],
        words: ['', ],
        definition: ['',],
        expressions: ['', ]
    },
    {
        id: uuidv4(),
        english: '',
        russian: '',
        grammar: [''],
        themes: [''],
        partOfSpeech: [''],
        words: ['', ],
        definition: ['',],
        expressions: ['', ]
    },
];




































