
export const initialWords = [
    {
        id: 'sdlk23234klsdfk',
        title: 'All words',
        english: '',
        partOfSpeech: "",
        themes: [],
    },
    {
        id: '2l3kj4l2k3lkj2lk3j4l',
        title: 'Convenient',
        english: 'convenient',
        partOfSpeech: "sldkjf230498",
        themes: [],
    },
    {
        id: '2lk3j4l2kj34l2hlkj23',
        title: 'Come over',
        english: 'come over',
        partOfSpeech: 'ksdljf29387',
        themes: [],
    },
    {
        id: 'sdfkjl23k4jl23j4',
        title: 'Come over (somebody)',
        english: 'come over (somebody)',
        partOfSpeech: 'ksdljf29387',
        themes: [],
    },
    {
        id: 'sldkfj02398425kjfs',
        title: 'speak / spoke / spoken',
        english: 'speak / spoke / spoken',
        partOfSpeech: 's;ldkf2394',
        themes: [],
    },
    {
        id: 'sdkfjl348203948skdf',
        title: 'get up',
        english: 'get up',
        partOfSpeech: 'ksdljf29387',
        themes: [],
    },
    {
        id: 'dfgj239r7sdfj237f',
        title: 'pick up',
        english: 'pick up',
        partOfSpeech: 'ksdljf29387',
        themes: [],
    },
    {
        id: 'sdfj3098fsdkj235',
        title: 'find out',
        english: 'find out',
        partOfSpeech: 'ksdljf29387',
        themes: [],
    },
    {
        id: 'sdflkj2398fsdkj23',
        title: '',
        english: '',
        partOfSpeech: '',
        themes: [],
    },
    {
        id: 'sdfjk2398fsdjf37fajs',
        title: '',
        english: '',
        partOfSpeech: '',
        themes: [],
    },
    {
        id: 'j239r8sdkj37fksdj3',
        title: '',
        english: '',
        partOfSpeech: '',
        themes: [],
    },
];