import {v4 as uuidv4} from 'uuid';

export const initialSentences = [
    {
        id: uuidv4(),
        english: 'If I stay here, will you let him go?',
        russian: 'Если я останусь здесь, ты отпустишь его?',
        grammar: ["kjsdf2834792837"],
        themes: [],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'Because if you don’t, I’ll divorce you.',
        russian: 'Потому что если ты этого не сделаешь, я с тобой разведусь.',
        grammar: ["kjsdf2834792837"],
        themes: ["slkdjflk34234"],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'If you push the button, two things will happen.',
        russian: 'Если вы нажмете кнопку, произойдут две вещи.',
        grammar: ["kjsdf2834792837"],
        themes: [],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'I’ll never be the same if we ever meet again.',
        russian: 'Я никогда не буду прежней, если мы когда-нибудь встретимся снова.',
        grammar: ["kjsdf2834792837"],
        themes: ["sldkjf34820934s"],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'If that was a movie, I would go see it.',
        russian: 'Если бы это был фильм, я бы сходил на него.',
        grammar: ["lsdjf298374"],
        themes: ["slkdjf23423"],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'If you weren’t my friend, there’d be a hole in my life.',
        russian: 'Если бы ты не был моим другом, в моей жизни была бы дыра.',
        grammar: ["lsdjf298374"],
        themes: ['conditional 2', "ewir2kj342lkj"],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'Would it be totally weird if I used it?',
        russian: 'Будет очень странно, если я воспользуюсь им?',
        grammar: ["lsdjf298374"],
        themes: ['conditional 2',],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'Would you dance if I asked you to dance?',
        russian: 'Ты бы потанцевала со мной, если бы я пригласил тебя на танец?',
        grammar: ["lsdjf298374"],
        themes: ['conditional 2', "ldkj234jk"],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'If you gave me a chance, I would take it.',
        russian: 'Если бы ты дал мне шанс, я бы им воспользовалась.',
        grammar: ["lsdjf298374"],
        themes: ['conditional 2', "sldkjf34820934s"],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'If you hadn’t been so rude to me, we wouldn’t have argued.',
        russian: 'Если бы ты не был груб со мной, мы бы не поругались.',
        grammar: ["023984lskdjf"],
        themes: ["sldkjf34820934s"],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'If I had set up an alarm clock, I wouldn’t have been late.',
        russian: 'Если бы я завел будильник, я бы не опоздал.',
        grammar: ["023984lskdjf"],
        themes: [],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'If I had left earlier, I wouldn’t have missed my flight.',
        russian: 'Если бы я выехал раньше, я бы не опоздал на рейс.',
        grammar: ["023984lskdjf"],
        themes: ["lsdkjf203984"],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'If she had replied to my message, I wouldn’t have been so worried.',
        russian: 'Если бы она ответила на мое сообщение, я бы так не волновался.',
        grammar: ["023984lskdjf"],
        themes: ["sldkjf34820934s"],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'She would have gotten this job, if she had better prepared for the interview.',
        russian: 'Она получила бы эту работу, если бы лучше подготовилась к собеседованию.',
        grammar: ["023984lskdjf"],
        themes: ["lkdjf23948"],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'If I had done a bit more research, I would have realized this hotel had terrible reviews.',
        russian: 'Если бы я поискал больше информации, я бы понял, что у этого отеля ужасные отзывы.',
        grammar: ["023984lskdjf"],
        themes: ["lsdkjf203984", "sldjflkj232342"],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'I’d like to choose daily skin care.',
        russian: 'Я бы хотела подобрать уход для кожи на каждый день.',
        grammar: [],
        themes: ["lskdjlk2342kj"],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'I prefer more natural products',
        russian: 'Я предпочитаю более натуральные средства',
        grammar: ["sdlkjf3487"],
        themes: ["lskdjlk2342kj"],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'preferably — fragrance-free and odorless',
        russian: 'желательно - без отдушек и запаха',
        grammar: [],
        themes: ["lskdjlk2342kj"],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'I’m looking for an exfoliating mask,',
        russian: 'Я ищу отшелушивающую маску-эксфолиант,',
        grammar: ["flkj2342jh"],
        themes: ["lskdjlk2342kj"],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'to cleanse my skin',
        russian: 'чтобы очищать кожу',
        grammar: [],
        themes: ["lskdjlk2342kj"],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'to eliminating dead cells / to exfoliate dead cells',
        russian: 'чтобы очищать кожу от мертвых клеток,',
        grammar: [],
        themes: ["lskdjlk2342kj"],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'to deeply cleanse the pores',
        russian: 'чтобы глубоко очищать поры',
        grammar: [],
        themes: ["lskdjlk2342kj"],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'to make my skin soft',
        russian: 'чтобы сделать кожу нежной,',
        grammar: [],
        themes: ["lskdjlk2342kj"],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'to make my skin look brighter and healthy',
        russian: 'чтобы делать мою кожу светлее и здоровее',
        grammar: ["flksj38472983"],
        themes: ["lskdjlk2342kj"],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'Will it make my skin look more healthy',
        russian: 'Это сделает кожу более здоровой на вид?',
        grammar: ["flksj38472983"],
        themes: ["lskdjlk2342kj"],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'I’d like a hyaluronic acid serum',
        russian: 'Я бы хотела серум с гиалуроновой кислотой',
        grammar: ["sdlkjf3487"],
        themes: ["lskdjlk2342kj"],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'to moisturize my skin',
        russian: 'чтобы увлажнить кожу',
        grammar: [],
        themes: ["lskdjlk2342kj"],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'As a night or winter cream',
        russian: 'В качестве ночного или зимнего крема',
        grammar: [],
        themes: ["lskdjlk2342kj"],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'I prefer nourishing cream with oils and herbal extracts',
        russian: 'Я предпочитаю питательный крем с маслами и растительными экстрактами',
        grammar: ["sdlkjf3487"],
        themes: ["lskdjlk2342kj"],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'to make my skin more lifted',
        russian: 'чтобы сделать кожу более подтянутой,',
        grammar: [],
        themes: ["lskdjlk2342kj"],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'to reduce fine lines and wrinkles',
        russian: 'чтобы уменьшить мелкие морщинки и складки',
        grammar: [],
        themes: ["lskdjlk2342kj"],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'with natural ingredients, fragrance-free and odorless',
        russian: 'с натуральными ингредиентами, без отдушек и запаха',
        grammar: [],
        themes: ["lskdjlk2342kj"],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'I`m looking for a product that will hide existing wrinkles',
        russian: 'Я ищу продукт, который скроет существующие морщинки',
        grammar: ["flkj2342jh"],
        themes: ["lskdjlk2342kj"],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'I`m looking for a product that will prevent new wrinkles from appearing.',
        russian: 'Я ищу продукт, который предотвратить появление новых морщин',
        grammar: ["flkj2342jh"],
        themes: ["lskdjlk2342kj"],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'I`d like to get a pronounced effect of tightening the skin',
        russian: 'Я бы хотела получить выраженный эффект подтяжки кожи',
        grammar: ["sdlkjf3487"],
        themes: ["lskdjlk2342kj"],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'that doesn`t need rinsing out',
        russian: 'который не нужно смывать',
        grammar: [],
        themes: ["lskdjlk2342kj"],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'Micellar Water is also ideal for cleansing your makeup before going to bed.',
        russian: 'Также мицеллярная вода идеально подходит для снятия макияжа перед сном.',
        grammar: [],
        themes: ["lskdjlk2342kj"],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'for smoothing out existing wrinkles',
        russian: 'для разглаживания существующих морщин ',
        grammar: [],
        themes: ["lskdjlk2342kj"],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'to reduce wrinkles, lighten and smooth the skin',
        russian: 'чтобы уменьшать морщины, осветлять и разглаживать кожу',
        grammar: [],
        themes: ["lskdjlk2342kj"],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'to reduce blemishes, wrinkles and other signs of aging',
        russian: 'чтобы уменьшить пятна, морщины и другие признаков старения',
        grammar: [],
        themes: ["lskdjlk2342kj"],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'Revitalizing Serum is a rich serum with a light texture',
        russian: 'Серум для восстановления кожи - это обогащенный серум, обладающий легкой текстурой.',
        grammar: [],
        themes: ["lskdjlk2342kj"],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'Anti-hair loss serum',
        russian: 'Серум против выпадения волос',
        grammar: [],
        themes: ["lskdjlk2342kj"],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'Our local shop has very convenient opening hours.',
        russian: 'У нашего местного магазина очень удобные часы работы.',
        grammar: ["sdlkjf3487"],
        themes: ["sldkjf234234"],
        partOfSpeech: ["sldkjf230498"],
        words: ['2l3kj4l2k3lkj2lk3j4l'],
        definition: ['sjkh3fhsk7293847293'],
    },
    {
        id: uuidv4(),
        english: 'A bike`s a very convenient way of getting around.',
        russian: 'Велосипед - очень удобный способ передвижения.',
        grammar: ["sdlkjf3487"],
        themes: ["sldkjf234234"],
        partOfSpeech: ["sldkjf230498"],
        words: ['2l3kj4l2k3lkj2lk3j4l'],
        definition: ['sjkh3fhsk7293847293'],
    },
    {
        id: uuidv4(),
        english: 'What time would it be convenient for me to come over?',
        russian: 'Во сколько мне будет удобно приехать?',
        grammar: [],
        themes: ['sldkjf34820934s'],
        partOfSpeech: ["sldkjf230498"],
        words: ['2l3kj4l2k3lkj2lk3j4l'],
        definition: ['sjkh3fhsk7293847293'],
    },
    {
        id: uuidv4(),
        english: 'It`s not really convenient for you to come this afternoon.',
        russian: 'Тебе не очень удобно приходить сегодня днем.',
        grammar: ["sdlkjf3487"],
        themes: ['sldkjf34820934s'],
        partOfSpeech: ["sldkjf230498"],
        words: ['2l3kj4l2k3lkj2lk3j4l'],
        definition: ['sjkh3fhsk7293847293'],
    },
    {
        id: uuidv4(),
        english: 'Would 3 o’clock be a convenient time to meet?',
        russian: 'З часа — удобное время для встречи?',
        grammar: [],
        themes: ['sldkjf34820934s'],
        partOfSpeech: ["sldkjf230498"],
        words: ['2l3kj4l2k3lkj2lk3j4l'],
        definition: ['sjkh3fhsk7293847293'],
    },
    {
        id: uuidv4(),
        english: 'a very convenient bus service',
        russian: 'очень удобное автобусное обслуживание',
        grammar: [],
        themes: ["lskdjf23423"],
        partOfSpeech: ["sldkjf230498"],
        words: ["2l3kj4l2k3lkj2lk3j4l"],
        definition: ['jksfhk34hj43234234hh4'],
    },
    {
        id: uuidv4(),
        english: 'Our new house is very convenient for the kids school.',
        russian: 'Наш новый дом очень удобен — он рядом со школой детей.',
        grammar: ["sdlkjf3487"],
        themes: ["sldkjf234234"],
        partOfSpeech: ["sldkjf230498"],
        words: ["2l3kj4l2k3lkj2lk3j4l"],
        definition: ['jksfhk34hj43234234hh4'],
    },
    {
        id: uuidv4(),
        english: 'Everything is convenient and reliable here.',
        russian: 'Здесь все очень удобно и надежно настроено.',
        grammar: ["sdlkjf3487"],
        themes: ["sldkjf234234"],
        partOfSpeech: ["sldkjf230498"],
        words: ["2l3kj4l2k3lkj2lk3j4l"],
        definition: ['sjkh3fhsk7293847293'],
    },
    {
        id: uuidv4(),
        english: 'This design is convenient for both women and men.',
        russian: 'Этот дизайн удобен как для женщин, так и для мужчин.',
        grammar: ["sdlkjf3487"],
        themes: ["sldkjf234234"],
        partOfSpeech: ["sldkjf230498"],
        words: ['2l3kj4l2k3lkj2lk3j4l'],
        definition: ['sjkh3fhsk7293847293'],
    },
    {
        id: uuidv4(),
        english: 'It is convenient to shops and the beach.',
        russian: 'Очень удобно расположен по отношению к магазинам и пляжу.',
        grammar: ["sdlkjf3487"],
        themes: ["sldkjf234234"],
        partOfSpeech: ["sldkjf230498"],
        words: ['2l3kj4l2k3lkj2lk3j4l'],
        definition: ['jksfhk34hj43234234hh4'],
    },
    {
        id: uuidv4(),
        english: 'Near the hotel: cafes, shops, market; convenient transport interchange.',
        russian: 'Рядом с отелем: кафе, магазины, рынок; удобная транспортная развязка.',
        grammar: [],
        themes: ["sldkjf234234"],
        partOfSpeech: ["sldkjf230498"],
        words: ['2l3kj4l2k3lkj2lk3j4l'],
        definition: ['jksfhk34hj43234234hh4'],
    },
    {
        id: uuidv4(),
        english: 'There are lots of shops around there and it was very convenient.',
        russian: 'Поблизости было много магазинов, что очень удобно.',
        grammar: ["sdlkjf3487"],
        themes: ["sldkjf234234"],
        partOfSpeech: ["sldkjf230498"],
        words: ['2l3kj4l2k3lkj2lk3j4l'],
        definition: ['jksfhk34hj43234234hh4'],
    },
    {
        id: uuidv4(),
        english: 'I watched the interview and felt he came over as quite arrogant.',
        russian: 'Я смотрел интервью и чувствовал, что он относится к высокомерному типу людей',
        grammar: ["fklj342342kj"],
        themes: ["sldkjf234234"],
        partOfSpeech: ["ksdljf29387"],
        words: ['2lk3j4l2kj34l2hlkj23'],
        definition: ['flskj42347987fsd'],
    },
    {
        id: uuidv4(),
        english: 'I think she comes over as very nervous.',
        russian: 'Я думаю, она относится к тому типу людей, которые очень нервничают',
        grammar: ["sdlkjf3487"],
        themes: ["sldkjf234234"],
        partOfSpeech: ["ksdljf29387"],
        words: ['2lk3j4l2kj34l2hlkj23'],
        definition: ['flskj42347987fsd'],
    },
    {
        id: uuidv4(),
        english: 'Come over here!',
        russian: 'Идите сюда!',
        grammar: ["flkj3423423"],
        themes: ['sldkjf34820934'],
        partOfSpeech: ["ksdljf29387"],
        words: ['2lk3j4l2kj34l2hlkj23',],
        definition: ['slkdfj28374928374'],
    },
    {
        id: uuidv4(),
        english: 'Is your family coming over from Greece for the wedding?',
        russian: 'Твоя семья приедет из Греции на свадьбу?',
        grammar: ["flkj2342jh"],
        themes: ['sldkjf34820934'],
        partOfSpeech: ["ksdljf29387"],
        words: ['2lk3j4l2kj34l2hlkj23',],
        definition: ['slkdfj28374928374'],
    },
    {
        id: uuidv4(),
        english: 'Ron came over for dinner.',
        russian: 'Рон приходил на ужин.',
        grammar: ["fklj342342kj"],
        themes: ['sldkjf34820934'],
        partOfSpeech: ["ksdljf29387"],
        words: ['2lk3j4l2kj34l2hlkj23',],
        definition: ['lfkj2414u12412jjj'],
    },
    {
        id: uuidv4(),
        english: 'I`m sorry! That was a stupid thing to say - I don`t know what came over me.',
        russian: 'Прости! Это было глупо - я не знаю, что на меня нашло.',
        grammar: ["fklj342342kj"],
        themes: ['sldkjf34820934'],
        partOfSpeech: ["ksdljf29387"],
        words: ['sdfkjl23k4jl23j4'],
        definition: ['sldkfj293847fsd'],
    },
    {
        id: uuidv4(),
        english: 'He gave you a present! What`s come over him?',
        russian: 'Он подарил тебе подарок! Что с ним?',
        grammar: ["fklj342342kj"],
        themes: ['sldkjf34820934'],
        partOfSpeech: ["ksdljf29387"],
        words: ['sdfkjl23k4jl23j4'],
        definition: ['sldkfj293847fsd'],
    },
    {
        id: uuidv4(),
        english: 'Would you mind speaking more slowly, please?',
        russian: 'Не могли бы вы говорить помедленнее, пожалуйста?',
        grammar: [],
        themes: ['lskdjflk3242'],
        partOfSpeech: ["s;ldkf2394"],
        words: ['sldkfj02398425kjfs'],
        definition: ['fjlk3523lkj235j23'],
    },
    {
        id: uuidv4(),
        english: 'Can I speak with Scott please?',
        russian: 'Могу я поговорить со Скоттом?',
        grammar: ["sldkfj238975"],
        themes: ['lskdjflk3242'],
        partOfSpeech: ["s;ldkf2394"],
        words: ['sldkfj02398425kjfs'],
        definition: ['fjlk3523lkj235j23'],
    },
    {
        id: uuidv4(),
        english: 'If he tells Julie what I said, I`ll never speak to him again.',
        russian: 'Если он скажет Джули то, что я сказал, я никогда с ним больше не заговорю.',
        grammar: ['kjsdf2834792837'],
        themes: ['sldkjf34820934'],
        partOfSpeech: ["s;ldkf2394"],
        words: ['sldkfj02398425kjfs'],
        definition: ['fjlk3523lkj235j23'],
    },
    {
        id: uuidv4(),
        english: 'She speaks very highly of the new director.',
        russian: 'Она очень высоко отзывается о новом директоре.',
        grammar: ["sdlkjf3487"],
        themes: ['sldkjf34820934'],
        partOfSpeech: ["s;ldkf2394"],
        words: ['sldkfj02398425kjfs'],
        definition: ['fjlk3523lkj235j23'],
    },
    {
        id: uuidv4(),
        english: 'I can certainly come but I can`t speak for my wife',
        russian: 'Я, конечно, могу прийти, но не могу говорить за свою жену.',
        grammar: ['sldkfj238975'],
        themes: ['sldkjf34820934'],
        partOfSpeech: ["s;ldkf2394"],
        words: ['sldkfj02398425kjfs'],
        definition: ['fjlk3523lkj235j23'],
    },
    {
        id: uuidv4(),
        english: 'He`s old enough to speak for himself.',
        russian: 'Он достаточно взрослый, чтобы говорить за себя.',
        grammar: ['sdlkjf3487'],
        themes: ['sldkjf34820934'],
        partOfSpeech: ["s;ldkf2394"],
        words: ['sldkfj02398425kjfs'],
        definition: ['fjlk3523lkj235j23'],
    },
    {
        id: uuidv4(),
        english: 'Speaking as a mother of four, I can tell you that children are exhausting.',
        russian: 'Говоря как мама четырех, я могу сказать вам, что дети изнурительны.',
        grammar: ['sldkfj238975'],
        themes: ['sldkjf34820934'],
        partOfSpeech: ["s;ldkf2394"],
        words: ['sldkfj02398425kjfs'],
        definition: ['fjlk3523lkj235j23'],
    },
    {
        id: uuidv4(),
        english: 'We`ve been invited to Rachel and Jamie`s wedding - speaking of which, did you know that they`re moving to New York?',
        russian: 'Нас пригласили на свадьбу Рейчел и Джейми, кстати говоря, ты знала, что они переезжают в Нью-Йорк?',
        grammar: ['slkj234234'],
        themes: ['ewir2kj342lkj'],
        partOfSpeech: ["s;ldkf2394"],
        words: ['sldkfj02398425kjfs'],
        definition: ['fjlk3523lkj235j23'],
    },
    {
        id: uuidv4(),
        english: 'Sue speaks with an American accent.',
        russian: 'Сью говорит с американским акцентом.',
        grammar: ['sdlkjf3487'],
        themes: [''],
        partOfSpeech: ["s;ldkf2394"],
        words: ['sldkfj02398425kjfs'],
        definition: ['fjlk3523lkj235j23'],
    },
    {
        id: uuidv4(),
        english: 'Why are you speaking in a whisper?',
        russian: 'Почему ты говоришь шепотом?',
        grammar: ['flkj2342jh'],
        themes: ['sldkjf34820934'],
        partOfSpeech: ["s;ldkf2394"],
        words: ['sldkfj02398425kjfs'],
        definition: ['fjlk3523lkj235j23'],
    },
    {
        id: uuidv4(),
        english: 'For five whole minutes, neither of them spoke a word.',
        russian: 'Целых пять минут ни один из них не говорил ни слова.',
        grammar: ['fklj342342kj'],
        themes: ['sldkjf34820934'],
        partOfSpeech: ["s;ldkf2394"],
        words: ['sldkfj02398425kjfs'],
        definition: ['fjlk3523lkj235j23'],
    },
    {
        id: uuidv4(),
        english: 'Could I speak to you privately?',
        russian: 'Могу я поговорить с вами наедине?',
        grammar: ['sldkfj238975'],
        themes: ['sldkjf34820934'],
        partOfSpeech: ["s;ldkf2394"],
        words: ['sldkfj02398425kjfs'],
        definition: ['fjlk3523lkj235j23'],
    },
    {
        id: uuidv4(),
        english: 'When last we spoke, you said you needed time.',
        russian: 'Когда мы говорили последний раз, ты говорила, что тебе нужно время.',
        grammar: ['fklj342342kj'],
        themes: ['sldkjf34820934'],
        partOfSpeech: ["s;ldkf2394"],
        words: ['sldkfj02398425kjfs'],
        definition: ['fjlk3523lkj235j23'],
    },
    {
        id: uuidv4(),
        english: 'He also spoke at the briefing.',
        russian: 'Во время брифинга он также выступил с речью.',
        grammar: ['fklj342342kj'],
        themes: ['sldkjf34820934'],
        partOfSpeech: ["s;ldkf2394"],
        words: ['sldkfj02398425kjfs'],
        definition: ['fjlk3523lkj235j23'],
    },
    {
        id: uuidv4(),
        english: 'Yes, I have spoken to him.',
        russian: 'Да, я говорил с ним.',
        grammar: ['slkj234234'],
        themes: ['sldkjf34820934'],
        partOfSpeech: ["s;ldkf2394"],
        words: ['sldkfj02398425kjfs'],
        definition: ['fjlk3523lkj235j23'],
    },
    {
        id: uuidv4(),
        english: ' Maybe, we should have spoken before this.',
        russian: 'Можно сказать, что мы должны были поговорить об этом раньше.',
        grammar: ['slkj234234'],
        themes: ['sldkjf34820934'],
        partOfSpeech: ["s;ldkf2394"],
        words: ['sldkfj02398425kjfs'],
        definition: ['fjlk3523lkj235j23'],
    },
    {
        id: uuidv4(),
        english: ' I think I have spoken enough about it.',
        russian: 'Я думаю, мы сказали достаточно по этому вопросу.',
        grammar: ['slkj234234'],
        themes: ['sldkjf34820934'],
        partOfSpeech: ["s;ldkf2394"],
        words: ['sldkfj02398425kjfs'],
        definition: ['fjlk3523lkj235j23'],
    },
    {
        id: uuidv4(),
        english: 'I have spoken about my experience previously.',
        russian: 'Я рассказала о своем опыте прежде.',
        grammar: ['slkj234234'],
        themes: ['sldkjf34820934'],
        partOfSpeech: ["s;ldkf2394"],
        words: ['sldkfj02398425kjfs'],
        definition: ['fjlk3523lkj235j23'],
    },

    {
        id: uuidv4(),
        english: 'I`d like to share with you guys, how beautiful it is here',
        russian: 'хочу поделиться с вами, как здесь красиво',
        grammar: [],
        themes: ['fj234d9fsj3jfsd'],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'This is ancient Greek civilization',
        russian: 'Это древняя греческая цивилизация',
        grammar: [],
        themes: ['fj234d9fsj3jfsd'],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'It was built before our era, more than 2000 years ago',
        russian: 'Это было построено до нашей эры, более 2000 лет назад',
        grammar: [],
        themes: ['fj234d9fsj3jfsd'],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'I finally got my favorite cappuccino at Starbucks',
        russian: 'я, наконец, получила мой любимый капучино в старбаксе,',
        grammar: [],
        themes: ['fj234d9fsj3jfsd'],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'we were here in January, and since then I’ve been dreaming about this pistachio ice cream',
        russian: 'мы были здесь в январе, и с тех пор я мечтала об этом фисташковом мороженом',
        grammar: [],
        themes: ['fj234d9fsj3jfsd'],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
    {
        id: uuidv4(),
        english: 'This place here is called Delphi',
        russian: 'Это место называется Дельфы',
        grammar: [],
        themes: ['fj234d9fsj3jfsd'],
        partOfSpeech: [],
        words: [],
        definition: [],
    },
];




























