
export const initialDefinitions = [
    {
        id: 'sjkh3fhsk7293847293',
        title: 'Подходит для ваших целей и потребностей и вызывает наименьшие трудности',
        english: 'convenient',
        wordId: "2l3kj4l2k3lkj2lk3j4l",
        russian: ['удобный', 'комфортный', 'подходящий', 'выгодный', 'целесообразный'],
        transcription: '/kənˈviː.ni.ənt/',
        definition: 'Подходит для ваших целей и потребностей и вызывает наименьшие трудности',
        partOfSpeech: "sldkjf230498",
        themes: [],
        status: 'in progress'
    },
    {
        id: 'jksfhk34hj43234234hh4',
        title: 'Близкий или легкий для получения или использования',
        english: 'convenient',
        wordId: "2l3kj4l2k3lkj2lk3j4l",
        russian: ['удобный', 'выгодный'],
        transcription: '/kənˈviː.ni.ənt/',
        definition: 'Близкий или легкий для получения или использования',
        partOfSpeech: "sldkjf230498",
        themes: [],
        status: 'to learn'

    },
    {
        id: 'flskj42347987fsd',
        title: 'Казаться человеком особого типа',
        english: 'come over',
        wordId: "2lk3j4l2kj34l2hlkj23",
        russian: ['показаться', 'кажется'],
        transcription: '/kʌm / + /ˈoʊ.vɚ/',
        definition: 'Казаться человеком особого типа',
        partOfSpeech: 'ksdljf29387',
        themes: [],
        status: 'done'

    },
    {
        id: 'slkdfj28374928374',
        title: 'Приходить на место, переезжать из одного места в другое, или двигаться к кому-то',
        english: 'come over',
        wordId: "2lk3j4l2kj34l2hlkj23",
        russian: ['прийти', 'приехать', 'подойти', 'зайти', 'заглянуть', 'заскочить', 'подъехать'],
        transcription: '/kʌm / + /ˈoʊ.vɚ/',
        definition: 'Приходить на место, переезжать из одного места в другое, или двигаться к кому-то',
        partOfSpeech: 'ksdljf29387',
        themes: [],
        status: 'todo'
    },
    {
        id: 'lfkj2414u12412jjj',
        title: 'Приходить к кому-то домой (USA)',
        english: 'come over',
        wordId: "2lk3j4l2kj34l2hlkj23",
        russian: ['прийти', 'приехать', 'подойти', 'зайти', 'заглянуть', 'заскочить', 'подъехать'],
        transcription: '/kʌm / + /ˈoʊ.vɚ/',
        definition: 'Приходить к кому-то домой (USA)',
        partOfSpeech: 'ksdljf29387',
        themes: [],
        status: 'todo'
    },
    {
        id: 'sldkfj293847fsd',
        title: 'Внезапно влиять на кого-то, заставляя вести себя определенным образом.',
        english: 'come over (somebody)',
        wordId: "sdfkjl23k4jl23j4",
        russian: ['нашло на меня/тебя/него и т. п.', 'что со мной/с ним/с ней'],
        transcription: '/kʌm / + /ˈoʊ.vɚ/',
        definition: 'Внезапно влиять на кого-то, заставляя вести себя определенным образом.',
        partOfSpeech: 'ksdljf29387',
        themes: [],
        status: 'todo'
    },
    {
        id: 'fjlk3523lkj235j23',
        title: 'Говорить слова, использовать голос, или разговаривать с кем-то',
        english: 'speak / spoke / spoken',
        wordId: "sldkfj02398425kjfs",
        russian: ['говорить', 'разговаривать', 'общаться', 'рассказать', ],
        transcription: '/spiːk/',
        definition: 'Говорить слова, использовать голос, или разговаривать с кем-то',
        partOfSpeech: 's;ldkf2394',
        themes: [],
        status: 'todo'
    },
    {
        id: 'dlkfj2398fdslkj398',
        title: 'Вставать с постели или заставлять кого-то вставать с постели',
        english: 'get (someone) up',
        wordId: "sdkfjl348203948skdf",
        russian: ['вставать', 'подниматься', 'просыпаться'],
        transcription: '/ɡet/ + /ʌp/',
        definition: 'Вставать с постели или заставлять кого-то вставать с постели',
        partOfSpeech: 'ksdljf29387',
        themes: [],
        status: 'todo'
    },
    {
        id: 'dfjk2398sdfkj398f',
        title: 'Ответить на телефонный звонок',
        english: 'pick up',
        wordId: "dfgj239r7sdfj237f",
        russian: ['взять трубку', 'снять трубку', 'подойти к телефону', 'ответить на звонок'],
        transcription: '/pɪk/ + /ʌp/',
        definition: 'Ответить на телефонный звонок',
        partOfSpeech: 'ksdljf29387',
        themes: [],
        status: 'todo'
    },
    {
        id: 'fjkj3487f9shk3jr7sd',
        title: 'Взять, забрать или принести кого-то или что-то откуда-то',
        english: 'pick up',
        wordId: "dfgj239r7sdfj237f",
        russian: ['взять', 'забрать', 'принести', 'привезти'],
        transcription: '/pɪk/ + /ʌp/',
        definition: 'Взять, забрать или принести кого-то или что-то откуда-то',
        partOfSpeech: 'ksdljf29387',
        themes: [],
        status: 'todo'
    },
    {
        id: 'fjl23kjf8se9df83hfslkd',
        title: 'Получить что-то просто так или спрашивая, прикладывая усилия или покупая.',
        english: 'pick up',
        wordId: "dfgj239r7sdfj237f",
        russian: ['снять', 'взять', 'получить',],
        transcription: '/pɪk/ + /ʌp/',
        definition: 'Получить что-то просто так или спрашивая, прикладывая усилия или покупая.',
        partOfSpeech: 'ksdljf29387',
        themes: [],
        status: 'todo'
    },
    {
        id: 'sdfdl348f7sjh34kjhsd',
        title: 'Получить информацию о чем-то, потому что вы хотите узнать больше об этом, или впервые узнать факт или часть информации.',
        english: 'find (something) out',
        wordId: "sdfj3098fsdkj235",
        russian: ['узнать', 'выяснить', 'разобраться', 'обнаружить'],
        transcription: '/faɪnd/ +  /aʊt/',
        definition: 'Получить информацию о чем-то, потому что вы хотите узнать больше об этом, или впервые узнать факт или часть информации.',
        partOfSpeech: 'ksdljf29387',
        themes: [],
        status: 'todo'
    },
    {
        id: 'elkrjelr89384eljeru',
        title: 'Использование одного человека или вещи вместо другого:',
        english: 'substitution',
        wordId: "sdflkj2398fsdkj23",
        russian: ['замена', 'подмена', 'замещение'],
        transcription: '/ˌsʌb.stəˈtuː.ʃən/',
        definition: 'использование одного человека или вещи вместо другого:',
        partOfSpeech: 'ksdljf29387',
        themes: ['dkfj3iusd9f3j', ],
        status: 'todo'
    },
    {
        id: 'elkrjelr89384eljeru',
        title: 'Если у вас есть пищевая непереносимость, вы не можете переварить конкретный продукт нормальным образом и может чувствовать себя плохо, если вы едите его',
        english: 'intolerance',
        wordId: "sdfjk2398fsdjf37fajs",
        russian: ['непереносимость',],
        transcription: '/ɪnˈtɑː.lɚ.əns/',
        definition: 'Если у вас есть пищевая непереносимость, вы не можете переварить конкретный продукт нормальным образом и может чувствовать себя плохо, если вы едите его',
        partOfSpeech: 'ksdljf29387',
        themes: [],
        status: 'todo'
    },
    {
        id: 'elkrjelr89384eljeru',
        title: '',
        english: '',
        wordId: "",
        russian: ['', '', '', ''],
        transcription: '// +  //',
        definition: '',
        partOfSpeech: 'ksdljf29387',
        themes: [],
        status: 'todo'
    },
]
