export const initialTrainingRoute = [
    {
        id: 'lksdjfl34134',
        userId: 'dlkfjl3487f9s',
        userRoute: [

            {
                id: 'fj234kljfd9s7f',
                name: 'Что такое грамматика',
                link: '/what-is-grammar',
                partOfGrammarId: 'fsldkjf323235',
                theory: '<p>Грамматика — это правила, которые помогают соединять между собой слова ...</p>  <p>Например, ...</p>',
                isOpen: true,
                isStudied: false,
                subThemes: [],
                isOpenSubThemes: true,
            },
            {
                id: '23480fjslkdjf',
                name: 'Как строить предложения',
                link: '/how-to-make-sentences',
                partOfGrammarId: "lkdj34234kjkj",
                theory: '<p>Предложение — это ...</p>  <p>Например, ...</p>',
                isOpen: true,
                isStudied: true,
                subThemes: [],
                isOpenSubThemes: true,
            },
            {
                id: 'dfj237s0f8hj4j2l',
                name: 'Что такое «время»',
                link: '/what-is-tense',
                partOfGrammarId: 'fjkl3k480s9fsdf',
                theory: '<p>Время (tense) — это ...</p>  <p>Например, ...</p>',
                isOpen: true,
                isStudied: true,
                subThemes: [],
                isOpenSubThemes: true,
            },
            {
                id: 'sdflkj234867s9d8',
                name: 'Present simple',
                link: '/present-simple',
                partOfGrammarId: "sdlkjf3487",
                isOpen: true,
                isStudied: false,
                isOpenSubThemes: true,
                subThemes: [
                    {
                        id: 'aslkj340sd9f8',
                        name: 'Present simple (positive statement)',
                        link: '/positive-in-present-simple',
                        partOfGrammarId: "sdlkfjl3427fdjf",
                        isOpen: true,
                        isStudied: false,
                    },
                    {
                        id: 'sdfkjl3029384',
                        name: 'Present simple (negative statement)',
                        link: '/negative-in-present-simple',
                        partOfGrammarId: "lksj347924sdfh",
                        isOpen: true,
                        isStudied: false,
                    },
                    {
                        id: 'ddlkfj234987324',
                        name: 'Present simple (question)',
                        link: '/question-in-present-simple',
                        partOfGrammarId: "dlfkj234jlkj34",
                        isOpen: true,
                        isStudied: false,
                    },
                ]
            },
            {
                id: 'sdfj2l347sdf723j',
                name: 'Present perfect',
                link: '/present-perfect',
                partOfGrammarId: "slkj234234",
                isOpen: true,
                isStudied: false,
                isOpenSubThemes: true,
                subThemes: [
                    {
                        id: 'djfl2308fsdfj',
                        name: 'Present perfect (positive statement)',
                        link: '/positive-in-present-perfect',
                        partOfGrammarId: "sldkfj3247987",
                        isOpen: true,
                        isStudied: false,
                    },
                    {
                        id: 'fdslkj2l3987fsdj2',
                        name: 'Present perfect (negative statement)',
                        link: '/negative-in-present-perfect',
                        partOfGrammarId: "dkfwher9237fsdf",
                        isOpen: true,
                        isStudied: false,
                    },
                    {
                        id: 'sdfj2l3k4987sfj32',
                        name: 'Present perfect (question)',
                        link: '/question-in-present-perfect',
                        partOfGrammarId: "djwlkej2387fsj3",
                        isOpen: true,
                        isStudied: false,
                    },
                ]
            },
            {
                id: 'dlkfj348723984',
                name: 'Conditionals',
                link: '/conditionals',
                partOfGrammarId: "sdlfkj23498s7f",
                isOpen: true,
                isStudied: false,
                isOpenSubThemes: true,
                subThemes: [
                    {
                        id: 'kjsdf2834792837',
                        name: 'conditional 1',
                        link: '/first-conditional',
                        partOfGrammarId: "kjsdf2834792837",
                        isOpen: true,
                        isStudied: false,
                    },
                    {
                        id: 'lsdjf298374',
                        name: 'conditional 2',
                        link: '/second-conditional',
                        partOfGrammarId: "lsdjf298374",
                        isOpen: true,
                        isStudied: false,
                    },
                    {
                        id: 'dfgj2340760235',
                        name: 'conditional 3',
                        link: '/third-conditional',
                        partOfGrammarId: "023984lskdjf",
                        isOpen: true,
                        isStudied: false,
                    },
                ]
            },
        ],
        userThemesRoute: [
            {
                id: 'dfkjl23r7sdf823j',
                name: 'For all occasions',
                link: '/for-all-occasions',
                partOfGrammarId: "",
                isOpen: true,
                isStudied: false,
                isOpenSubThemes: true,
                subThemes: [
                    {
                        id: 'sldkjf2398f0s9dfk',
                        name: 'Clarify possible misunderstandings',
                        link: '/clarify-possible-misunderstandings',
                        partOfGrammarId: "",
                        isOpen: true,
                        isStudied: false,
                    },
                    {
                        id: 'dflkj98fs098kjfd',
                        name: 'How to be polite',
                        link: '/how-to-be-polite',
                        partOfGrammarId: "",
                        isOpen: true,
                        isStudied: false,
                    },
                    {
                        id: 'kj38f0s98fj23f8dsdf',
                        name: 'Set expressions',
                        link: '/set expressions',
                        partOfGrammarId: "",
                        isOpen: true,
                        isStudied: false,
                    },
                ]
            },
            {
                id: 'dlj23r80s9d8flkj3',
                name: 'Arranging travel & situations on the way',
                link: '/arranging-travel',
                partOfGrammarId: "",
                isOpen: true,
                isStudied: false,
                isOpenSubThemes: true,
                subThemes: [
                    {
                        id: 'fslkj387fs98d72',
                        name: 'Renting a car',
                        link: '/renting-a-car',
                        partOfGrammarId: "",
                        isOpen: true,
                        isStudied: false,
                    },
                    {
                        id: 'dlkj2387fs98d2j34h',
                        name: 'On the border',
                        link: '/on-the-border',
                        partOfGrammarId: "",
                        isOpen: true,
                        isStudied: false,
                    },
                    {
                        id: 'sdflkj23987sdfjh287',
                        name: 'At the hotel',
                        link: '/at-the-hotel',
                        partOfGrammarId: "",
                        isOpen: true,
                        isStudied: false,
                    },
                ]
            },
            {
                id: '34hk2cfudydf234',
                name: 'Vacation itself',
                link: '/vacation itself',
                partOfGrammarId: "",
                isOpen: true,
                isStudied: false,
                isOpenSubThemes: true,
                subThemes: [
                    {
                        id: 'fdkjsh23oufsdf',
                        name: 'Restaurant',
                        link: '/restaurant',
                        partOfGrammarId: "dkfj3iusd9f3",
                        isOpen: true,
                        isStudied: false,
                    },
                    {
                        id: '23fjsdjf23oiuf',
                        name: 'Asking for directions.',
                        link: '/asking-for-directions.',
                        partOfGrammarId: "",
                        isOpen: true,
                        isStudied: false,
                    },
                ]
            },
        ]
    },
    {
        id: 'sdlkj348203948667',
        userId: 'dfjl3409s9df8hfhf',
        userRoute: [],
    }
]